#### Array implimentations for coders

In [1]:
# Find subarray with given sum with O(n) 
# Ex: [-10, 0, 2, -2, -20, 10] find the sub-array with a sum = -12, (recursion would be O(n!))

def sub_array_sum(flow_arr, target):
    s = [] 
    sum_of_items = 0
    n = len(flow_arr) 
    for i in range(n): 
        sum_of_items += flow_arr[i] 
        s.append(sum_of_items) 
        if sum_of_items == target:
            return flow_arr[:i+1]

    for each_sum in range(len(s)):
        item = s[each_sum]
        if item-target in s:
            mark_the_last_index = s.index(item) # last seen repetition's index is marked 
            mark_the_first_index = s.index(item-target)
        
            # print(s, mark_the_first_index, mark_the_last_index) # to view the indices if needed
            return flow_arr[mark_the_first_index+1: mark_the_last_index+1]   
    
    return None
    
test = [-9, 0, 2, -2, -20, 10] 

sub_array_sum(test, -12)



[-2, -20, 10]

In [2]:
# Find zero sum sub-array 
# If sum of all items list have two numbers repeating each other, it means there is a zero sum sub array in between 
# the repeating numbers

def find_zero_sum_subarray(flow_arr):
    
    s = [] 
    sum_of_items = 0
    n = len(flow_arr) 
    for i in range(n): 
        sum_of_items += flow_arr[i] 
        s.append(sum_of_items) 
        if sum_of_items == 0:
            return flow_arr[:i+1]

    # if nothing summed up to 0 but all items are summed to some several other values, 
    # add all items in a dictionary to see if there are any double values
    a_dict = {}
    for each_sum in range(len(s)):
        item = s[each_sum]
        if item in a_dict:
            a_dict[item] += 1
            mark_the_index = each_sum # last seen repetition's index is marked 
        else:
            a_dict[item] = 1
    print(s, a_dict) # to view the duplicates if needed
   
    # mark the values of the dictinary if there are two items that has the same sum value
    for k in a_dict.keys():
        v = a_dict[k]
        if v > 1: # if the item is seen more than once 
            start_index = s.index(mark_the_index) # python built-in method only shows the first index that item is seen
            end_index = mark_the_index 
            # start index is not included but mark index is included since sub-array summing 0 starts after 
            return flow_arr[start_index+1 : mark_the_index+1] # sum array : [4, 6, 3, 4, 10] 
    
    return None

test_2 = [4, 2, -5, -1, 6, -2]

find_zero_sum_subarray(test_2)



[4, 2, -5, -1]

In [3]:
# Find Triplets Algorithm O(N^2)
# Find if sum of two elements in an array is equal to one of the elements in the same array

def find_triplets(arr): 
    n = len(arr)
    # sort the array 
    arr.sort() 
    # start from both sides of a sorted array and see if the sum is matching the largest item
    # continue to look for the latter largest elements percolating from the end index to the start index
    i = n - 1
    while(i >= 0): 
        j = 0
        k = i-1
        while (j < k): 
            if (arr[i] == arr[j] + arr[k]): 
                return arr[i], arr[j], arr[k] 
            elif (arr[i] > arr[j] + arr[k]): 
                j += 1
            elif (arr[i] < arr[j] + arr[k]): 
                k -= 1
        i -= 1
          
    return None

arr = [2, 6, -1, 9, 4, 3] 
find_triplets(arr)

(9, 3, 6)

In [4]:
# Answer to the "max sub-array sum problem" that is widely available at several online sources

def maxSubArraySum(a): 
    n = len(a)
    max_so_far = a[0] 
    curr_max = a[0] 
    for i in range(1,n): 
        curr_max = max(a[i], curr_max + a[i]) 
        max_so_far = max(max_so_far, curr_max) 
          
    return max_so_far 
  
a = [-2, -3, 4, -1, 6 -2, 1, 5, -3, 1] 
maxSubArraySum(a) 
 


13

In [5]:
# Max sub-array sum problem extracting the items from the array 
# Print the MOST PROFITABLE subarray, just a more comprehensive solution than the one above 

import numpy as np
def maxSubArraySum(a): 
    sum_of_items = []
    sum = 0
    for i in range(len(a)): 
        sum += a[i]
        sum_of_items.append(sum)
    max_item = max(sum_of_items)
    max_at_ind = sum_of_items.index(max_item)
    # print(a, sum_of_items, max_item, max_at_ind) # to view
    
    # start from the max item and go backwards by summing up the total
    # find the second largest number until the max_at_ind
    sum_of_items2 = [] 
    total = 0
    max_sum = 0
    for j in reversed(range(0, max_at_ind)):
        item = a[j]
        total += item
        sum_of_items2.append(total)
        if max_sum < total:
            max_sum = total
            # count how many steps taken to reach the maximum 
            diff = max_at_ind - j
    
    # print('sum of items', sum_of_items2, diff) # to view the second sum intes
    return a[max_at_ind - diff: max_at_ind+1]
   
    
a = [-2, -3, 4, -1, 6 -2, 1, 5, -3, 1] 
maxSubArraySum(a) 
 


[4, -1, 4, 1, 5]

In [6]:
# Get the missing number of an arithmetic sequence starting from 1.
# Formula: sum of numbers is total = n*(n+1)/2
# Subtract all the numbers from sum and you will get the missing number

def find_missing_numb_of_arithmetic_series(a): 
    n = len(a) 
    total = (n + 1)*(n + 2)/2
    sum_of_A = sum(a) 
    return total - sum_of_A 
  

test = [1, 2, 4, 5, 6] 
find_missing_numb_of_arithmetic_series(test)


3.0

In [7]:
# merge unsorted arrays and merge sorted arrays

def split(n):
    if len(n) <= 1: return n
    mid = len(n)//2
    left = n[:mid]
    right = n[mid:]
    return left, right


def merge_sorted_two_arrays(a, b):
    if len(a) == 0: return b
    if len(b) == 0: return a
    i = 0
    j = 0
    list_of_merged = []
    while i < len(a) and j < len(b):
        if a[i] < b[j]:
            list_of_merged.append(a[i])
            i += 1
        elif a[i] > b[j]:
            list_of_merged.append(b[j])
            j += 1
        else: # if a[i] == b[j]
            list_of_merged.append(a[i])
            list_of_merged.append(b[j])
            i += 1
            j += 1
        if i == len(a):
            for k in range(j, len(b)):
                list_of_merged.append(b[j])
        if j == len(b):
            for k in range(i, len(a)):
                list_of_merged.append(a[i])
    return list_of_merged


def merge_sort(n):
    if len(n) <= 1: return n
    left, right = split(n)
    left_splits = merge_sort(left)
    right_splits = merge_sort(right)
    combine_splits = merge_sorted_two_arrays(left_splits, right_splits)
    return combine_splits
    
test_array = [2,3,6,6,1,-2,13,0]
    
merge_sort(test_array)

[-2, 0, 1, 2, 3, 6, 6, 13]

In [8]:
# Rearrange an array alternatively in a way that the max, min, secondmax, secondmin.... all elements are reordered

test_array = [2,3,6,6,1,-2,13,0]
sorted_array = np.sort(test_array)
rearranged_array = []
assert(len(sorted_array) > 1)
for i in range(len(sorted_array)):
    high_index = len(sorted_array)-1-i
    low_index = i
    print(high_index, low_index)
    if high_index <= low_index: break 
    # VERY important: if len(array) is odd: this never happens: high index == low index so <= sign is crucial
    # Example: 7-0 , 6-1, 5-2, 4-3, 3-4, stop here. So 3==3 or 4==4 didn't happen.
    rearranged_array.append(sorted_array[high_index])
    rearranged_array.append(sorted_array[low_index])

print(rearranged_array)


7 0
6 1
5 2
4 3
3 4
[13, -2, 6, 0, 6, 1, 3, 2]


In [9]:
# The number of inversions of an array shows how far this array is away from being sorted. if it is 0 it is sorted.
# Find the inversions of an array using merge sort

def merge_sort_w_inversion_count(arr):
    inversions = 0
    if len(arr) == 1: return arr, inversions
    left = arr[:len(arr)//2]
    right = arr[len(arr)//2:]
    a, ai = merge_sort_w_inversion_count(left)
    b, bi = merge_sort_w_inversion_count(right)
    inversions = ai + bi
    # merge two sorted arrays a and b
    combine = [] 
    i = 0
    j = 0
    while i < len(a) and j < len(b):
        if a[i] < b[j]:
            combine.append(a[i])
            i += 1
        elif a[i] > b[j]:
            combine.append(b[j])
            j += 1
            inversions += 1     
        else:
            combine.append(a[i])
            combine.append(b[j])
            i += 1
            j += 1
            
        if i == len(a):
            for k in range(j, len(b)):
                combine.append(b[k])
        if j == len(b):
            for k in range(i, len(a)):
                combine.append(a[k])
                inversions += 1
    
    # print(arr, a, b, inversions)                   
    return combine, inversions
    

test_array2 = [3,2,1,8]
print(merge_sort_w_inversion_count(test_array2))

# test_array = [2,3,6,6,1,-2,13,0]
# merge_sort_w_inversion_count(test_array)


([1, 2, 3, 8], 3)


In [10]:
# Find number of pairs (x, y) in an array such that x^y > y^x    Ex: X = {2, 1, 6}, Y = {1, 5} # Output: 3
# Explanation: There are total 3 pairs where pow(x, y) is greater than pow(y, x) Pairs are (2, 1), (2, 5) and (6, 1)

# Brute force O(n**2) embarrasingly bad solution
X = [2,1,6]
Y = [1,5]
items = []
for i in range(len(X)):
    for j in range(len(Y)):
        if X[i]**Y[j] > Y[j]**X[i]:
            items.append([X[i], Y[j]])
print(items)
            

[[2, 1], [2, 5], [6, 1]]


In [11]:
# Sort an array of 0s, 1s and 2s in O(n) time
# Input: {0, 1, 1, 0, 1, 2, 1, 2, 0, 0, 0, 1}  Output: {0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2} in one pass

# Function to sort array 
def sort012array(a):
    n = len(a)
    lo = 0
    hi = n - 1
    mid = 0
    while mid <= hi: 
        if a[mid] == 0: 
            a[lo], a[mid] = a[mid], a[lo] 
            lo = lo + 1
            mid = mid + 1
        elif a[mid] == 1: 
            mid = mid + 1
        else: 
            a[mid], a[hi] = a[hi], a[mid]  
            hi = hi - 1
    return a 
       
test_array = [0, 1, 1, 0, 1, 2, 1, 2, 0, 0, 0, 1] 
sort012array(test_array)



[0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2]

In [12]:
# Without changing the location of items, find the equilibrium index of an array where left side sum == right side sum

def equilibrium(arr): 
    leftsum = 0
    rightsum = 0
    n = len(arr) 
  
    for i in range(n): 
        leftsum = 0
        rightsum = 0

        for j in range(i): 
            leftsum += arr[j] 

        for j in range(i + 1, n): 
            rightsum += arr[j] 

        if leftsum == rightsum: 
            return i 
      
    # return -1 if no equilibrium index is found 
    return -1
              
# driver code 
arr = [-7, -1, 5, -2, -4, -2, 0] 
equilibrium(arr) 

2

In [13]:
# Find the "leaders in an array". An element is leader if it is greater than all the elements to its right side
# Note: last element is always in this list

def printLeaders(a): 
    n = len(a)
    items = []
    max_from_right = a[n-1]         
    for i in reversed(range(0, n)):         
        if max_from_right <= a[i]:             
            max_from_right = a[i] 
            items.insert(0, a[i])
    return items

arr = [16, 17, 4, 3, 5, 2]
printLeaders(arr)

[17, 5, 2]

In [14]:
# Find the Minimum Number of Platforms Required for a Railway / Bus Station
# Inbound = {9:00, 9:40, 9:50, 11:00, 15:00, 18:00}    
# Outbound = {9:10, 12:00, 11:20, 11:30, 19:00, 20:00}
# Output: 3.There are at-most three trains at a time (time between 11:00 to 11:20)  
# 9:40 train is there until 12 , 9:50 train is there until 11:20, 11:00 train is the third train entering

def findPlatform(arr,dep): 
    assert(len(arr)== len(dep))
    n = len(arr)
    arr.sort() 
    dep.sort() 
    plat_needed = 0  # current number of platforms needed through first train to last train 
    max_platforms_needed = 0
    i = 0
    j = 0
   
    while (i < n and j < n): 
        if (arr[i] < dep[j]): 
            plat_needed+=1
            i+=1 
            if (plat_needed > max_platforms_needed):  
                 max_platforms_needed = plat_needed   
        else: 
            plat_needed-=1
            j+=1
          
    return max_platforms_needed 
  
# driver code 
  
arr = [900, 940, 950, 1100, 1500, 1800] 
dep = [910, 1200, 1120, 1130, 1900, 2000] 
findPlatform(arr, dep) 


3

In [15]:
# Reverse array in k groups 
# Ex: arr = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]  k = 3 output: [3, 2, 1, 6, 5, 4, 9, 8, 7, 11]

import numpy as np
input_array = np.arange(1, 11, dtype = int)
print(input_array)
def reverse_array_each_k(array, k):
    rev_k = []
    n = len(array)
    array_with_k = []
    for i in range(n):
        array_with_k.insert(0,array[i])
        if len(array_with_k) == 3:
            rev_k += array_with_k
            array_with_k = []
    return rev_k + array_with_k
        
reverse_array_each_k(input_array, 3)
        

[ 1  2  3  4  5  6  7  8  9 10]


[3, 2, 1, 6, 5, 4, 9, 8, 7, 10]

In [16]:
# find kth smallest element of an unsorted array

unsorted_array = [13, 12, -1, 6, -5, 14, 9, 8, 7, 10]

def sort_array(unsorted_array):
    if len(unsorted_array) <= 1: return unsorted_array
    mid = len(unsorted_array) // 2
    pivot = unsorted_array[mid]
    left = [unsorted_array[i] for i in range(len(unsorted_array)) if unsorted_array[i] < pivot]
    mid = [unsorted_array[i] for i in range(len(unsorted_array)) if unsorted_array[i] == pivot]
    right = [unsorted_array[i] for i in range(len(unsorted_array)) if unsorted_array[i] > pivot]
    sort_all = sort_array(left) + mid + sort_array(right)
    return sort_all
    
sorted_array = sort_array(unsorted_array)
print(sorted_array)
# if k = 3 for third smallest element the item is at index 2 Ex: The smallest element would be at index 0
print(sorted_array[2])


[-5, -1, 6, 7, 8, 9, 10, 12, 13, 14]
6


In [17]:
# Famous fizzbuzz question where order matters to print the solution

for num in range(1, 17):
    if num % 15 is 0:
        print("FizzBuzz")
    elif num % 3 is 0:
        print("Fizz")
    elif num % 5 is 0:
        print("Buzz")
    else:
        print(num)

1
2
Fizz
4
Buzz
Fizz
7
8
Fizz
Buzz
11
Fizz
13
14
FizzBuzz
16


In [18]:
def findWater(arr, n): 
  
    # left[i] contains height of tallest bar to the 
    # left of i'th bar including itself 
    left = [0]*n 
  
    # Right [i] contains height of tallest bar to 
    # the right of ith bar including itself 
    right = [0]*n 
  
    # Initialize result 
    water = 0
  
    # Fill left array 
    left[0] = arr[0] 
    for i in range( 1, n): 
        left[i] = max(left[i-1], arr[i]) 
  
    # Fill right array 
    right[n-1] = arr[n-1] 
    for i in range(n-2, -1, -1): 
        right[i] = max(right[i + 1], arr[i]); 
  
    # Calculate the accumulated water element by element 
    # consider the amount of water on i'th bar, the 
    # amount of water accumulated on this particular 
    # bar will be equal to min(left[i], right[i]) - arr[i] . 
    for i in range(0, n): 
        water += min(left[i], right[i]) - arr[i] 
  
    return water 

arr = [0, 1, 0, 2, 1, 0, 1, 3, 2, 1, 2, 1] 
n = len(arr) 
print("Maximum water that can be accumulated is", findWater(arr, n)) 

#         | 
#     |xxx||x|
# _|x|||x|||||
# Trap "1 unit" between first 1 and 2, "4 units" between
# first 2 and 3 and "1 unit" between second last 1 and last 2 

Maximum water that can be accumulated is 6


In [19]:
# Finding pythogorian triplets in array Using Hashing. The time complexity will be O(max, max) max element of the array
# Find if a2 + b2 = c2 in an array  Example:  Input: arr[] = {3, 1, 4, 6, 5} Output: True (3, 4, 5)

import math 
  
def checkTriplet(arr, n): 
    maximum = 0
  
    # Find the maximum element 
    for i in range(n): 
        maximum = max(maximum, arr[i]) 
  
        # Hashing array 
    hash = [0]*(maximum+1) 
  
    # Increase the count of array elements 
    # in hash table 
    for i in range(n): 
        hash[arr[i]] += 1
  
        # Iterate for all possible a 
    for i in range(1, maximum+1): 
        # If a is not there 
        if (hash[i] == 0): 
            continue
  
        # Iterate for all possible b 
        for j in range(1, maximum+1): 
            # If a and b are same and there is only one a 
            # or if there is no b in original array 
            if ((i == j and hash[i] == 1) or hash[j] == 0): 
                continue
  
            # Find c 
            val = int(math.sqrt(i * i + j * j)) 
  
            # If c^2 is not a perfect square 
            if ((val * val) != (i * i + j * j)): 
                continue
  
            # If c exceeds the maximum value 
            if (val > maximum): 
                continue
  
            # If there exists c in the original array, 
            # we have the triplet 
            if (hash[val]): 
                return True
    return False
  
arr = [3, 2, 4, 6, 5] 
n = len(arr) 
if (checkTriplet(arr, n)): 
    print("Yes") 
else: 
    print("No")

Yes


In [20]:
# Find m number of points in an array where min-max diff would be minimum of a subarray with size m
# Answer to minimize difference between maximum and minimum. The well-known "Chocolate Distribution Question" 

# Ex: Array = [12, 4, 7, 9, 2, 23, 25, 41, 30, 40, 28, 42, 30, 44, 48, 43, 50]
# m = 7 packages will be distributed, which packages should be distributed?
# Output: Minimum Difference is 10 if we need to pick 7 packets: 40, 41, 42, 44, 48, 43 and 50 

def find_smallest_min_max_sub_array(array, m):
    array = np.sort(array)
    n = len(array)
    if m > n: return
    diff = np.inf
    for i in range(0, len(array)-m):
        sub_array = array[i: i+m]
        minimum = min(sub_array)
        maximum = max(sub_array)
        if maximum - minimum < diff:
            diff = maximum - minimum
            mark_the_starting_ind = i
    return array[i: i+ m+1]
            
test_array = [12, 4, 7, 9, 2, 23, 25, 41, 30, 40, 28, 42, 30, 44, 48, 43, 50]    
find_smallest_min_max_sub_array(test_array, 6)


   

array([40, 41, 42, 43, 44, 48, 50])

In [21]:
# Python program to maximize the profit by doing at most k transactions given stock prices for n days 
# Function to find out maximum profit by buying & selling a share atmost k times  given stock price of n days 

def maxProfit(prices, k): 
    n = len(prices)
    if k > n: return
    # Bottom-up DP approach 
    profit = np.zeros([n, k+1]) 
    # Profit is zero for the first 
    # day and for zero transactions 
    for i in range(1, n): # for each day's stock value
        for j in range(1, k+1): # for each transaction 
            max_so_far = 0
            for l in range(i): # for all past transactions
                max_so_far = max(max_so_far, prices[i] - prices[l] + profit[l][j-1])               
            profit[i][j] = max(profit[i - 1][j], max_so_far) 
    
    print(profit) # to view the table
    return profit[n - 1][k] 
  
# Driver code 
k = 3
prices = [10, 22, 5, 75, 65, 80] 
n = len(prices) 
  
print("Maximum profit is:", maxProfit(prices, k)) 
  
# if k = 2, trader earns 87 as sum of 12 and 75 Buy at price 10, sell at 22, buy at 5 and sell at 80,

[[ 0.  0.  0.  0.]
 [ 0. 12. 12. 12.]
 [ 0. 12. 12. 12.]
 [ 0. 70. 82. 82.]
 [ 0. 70. 82. 82.]
 [ 0. 75. 87. 97.]]
Maximum profit is: 97.0


In [22]:
# Alternative aolution to maximize the profit by doing at most k transactions given stock prices for n days 

import numpy as np
def maximize_profit_with_k_trsc(price_list, k):
    n = len(price_list)
    if n <= 1 or k > len(price_list): return 0
    memo_table = np.zeros([k+1, n] , dtype = int)  # number of transactions in rows
    for i in range(1, k+1): # for each buy and sell transaction, i
        max_profit = -np.inf
        for j in range(1, len(price_list)): # for each day, j
            prev_day_prev_transact = memo_table[i-1][j-1] # max profit until prev day and prev transact
            prev_day_price = price_list[j-1]
            max_transaction_until_prev_day = memo_table[i][j-1] 
            price_today = price_list[j]
            max_profit = max(max_profit, prev_day_prev_transact - prev_day_price)
            memo_table[i][j] = max(max_transaction_until_prev_day, max_profit + price_today)
    
    print(memo_table)
    return memo_table[k][n-1]      
            
prices = [10, 22, 5, 75, 65, 80] 
maximize_profit_with_k_trsc(prices, 3)

[[ 0  0  0  0  0  0]
 [ 0 12 12 70 70 75]
 [ 0 12 12 82 82 87]
 [ 0 12 12 82 82 97]]


97

In [23]:
# Find the element before which all the elements are smaller than it, and after which all elements are greater

def find_the_element_at_pivot(array):
    if len(array) <= 1: return None
    for i in range(len(array)): # for all the elements in the array
        all_elements_before = array[:i+1]
        assert(len(all_elements_before) != 0)
        all_elements_after = array[i:]
        assert(len(all_elements_after) != 0)
        if array[i] == max(all_elements_before) and array[i] == min(all_elements_after):
            return array[i]

find_the_element_at_pivot([5, 1, 4, 3, 6, 8, 10, 7, 9]) # The answer should be 6
    

6

In [24]:
# make a zigzag pattern where A < B > C < D > E... the element in odd index is bigger than the elements at both sides

import numpy as np

def zigzag(array):
    n = len(array)
    sorted_array = np.sort(array)
    for i in range(1, n-1):
        if i % 2 == 1:
            sorted_array[i], sorted_array[i+1] = sorted_array[i+1], sorted_array[i]
    zigzaged_array = sorted_array
    return zigzaged_array

test_array = [1,6,8,9,2,6,4,7,0,7,8]

zigzag(test_array)

    

array([0, 2, 1, 6, 4, 7, 6, 8, 7, 9, 8])

In [25]:
# Find the index of first 1 in a sorted array of 0’s and 1’s
# Given a sorted array consisting 0’s and 1’s. The problem is to find the index of first ‘1’ in the sorted array. 
# It could be possible that the array consists of only 0’s or only 1’s. 
# If 1’s are not present in the array then print “-1”.

def find_index_of_first_1(sorted_array): # sorted array is of 0 and 1
    if len(sorted_array) == 0: 
        return 
    n = len(sorted_array)
    # if last element is 0 it will return -1
    if sorted_array[n-1] == 0: return -1
    for i in range(len(sorted_array)):
        if sorted_array[i] == 1:
            return i
        
find_index_of_first_1([0, 0, 1, 1])
        
    


2

In [26]:
# Python3 program to print given matrix in spiral form 

def spiralPrint(a) :
    
    k = 0 # k - starting row index             k,l      n
    l = 0 # l - starting column index 
    m = len(a) # m - ending row index           m
    n = len(a[0]) # n - ending column index 
    spiral_read = []

    while (k < m and l < n) : 
          
        # Print the first row then increase the row number by one 
        for i in range(l, n) : 
            spiral_read.append(a[k][i]) 
              
        k += 1
  
        # Print the last column from the remaining columns  
        for i in range(k, m) : 
            spiral_read.append(a[i][n - 1]) 
              
        n -= 1
  
        # Print the last row from 
        # the remaining rows  
        if (k < m) : 
              
            for i in range(n - 1, (l - 1), -1) : 
                spiral_read.append(a[m - 1][i]) 
              
            m -= 1
          
        # Print the first column from the remaining columns  
        if (l < n) : 
            for i in range(m - 1, k - 1, -1) : 
                spiral_read.append(a[i][l]) 
              
            l += 1
        return spiral_read

a = [[1, 2, 3], 
     [7, 4, 9], 
     [5 ,3, 8]] 
        

spiralPrint(a) 
  

[1, 2, 3, 9, 8, 3, 5, 7]

In [27]:
# turn matrix counter clock direction and solve the above problem with a horrible space complexity

import numpy as np

test_m = [[1,2,3,4],
          [5,6,7,8],
          [9,10,11,12]]

def turn_matrix_counter_clock(m):
    if len(m) == 0: return
    row_length = len(m)
    column_length = len(m[0])
    turned_m = []
    for j in reversed(range(column_length)):
        inner_list = []
        for i in range(row_length):
            inner_list.append(m[i][j])
        turned_m.append(inner_list)
    return turned_m

new_m = turn_matrix_counter_clock(test_m)
print('90 degrees rotated matrix in counter clock wise', new_m)

# print a matrix in spiral form 

def print_m_spiral(m):
    if len(m) == 0: return
    spiral_m = []
    while m != None:
        spiral_m.extend(m[0])
        m_new = m[1:][:]
        m = turn_matrix_counter_clock(m_new)    
    return spiral_m
    
                                 
print_m_spiral(test_m)


90 degrees rotated matrix in counter clock wise [[4, 8, 12], [3, 7, 11], [2, 6, 10], [1, 5, 9]]


[1, 2, 3, 4, 8, 12, 11, 10, 9, 5, 6, 7]

In [29]:
# Arrange given numbers to form the biggest number 
# Given an array of numbers, arrange them in a way that yields the largest value. 
# For example, if the given numbers are {54, 546, 548, 60}, 
# the arrangement 6054854654 gives the largest value. 
# And if the given numbers are {1, 34, 3, 98, 9, 76, 45, 4}, then the arrangement 998764543431 gives the largest value

 
def permutate(number_set, results = None, solutions = None): # to not to store the mutable default arguments in memory
    if results == None: results = []
    if solutions == None: solutions = []
    if len(number_set) == 0: 
        results.append(solutions)
        return
    for i, n in enumerate(number_set):
        remaining = number_set[:i] + number_set[i+1:]
        if remaining != None:
            permutate(remaining, results, solutions + [n])
    return results

    
def return_highest_val(array):
    items = []
    for item in array:
        str_a = [str(i) for i in item]
        comb = "".join(str_a)
        int_comb = int(comb)
        items.append(int_comb)
    return max(items)



set_of_items = [1, 34, 3, 98, 9, 76, 45, 4]
perm_of_set_of_items = permutate(set_of_items)
return_highest_val(perm_of_set_of_items)

998764543431