In [1]:
# Finding sum of N primes that is equal to S if smallest prime starts from P

# Find if a number is prime with fermat's test
def is_prime(n) : 
    if n <= 1: return False # first prime number is 2
    if n % 2 == 0: return False # If number is even, it's a composite number
    for i in range(2, n):  # if any number is yielding other than 1 it is not prime. 
        check_if_prime = ((i**(n-1) % n) == 1) # so this formula needs to be true for all numbers of "i"
        if check_if_prime == False:  
            return False
    return True


# Find all numbers between P and S and put it in all_prime_numbers_list
def find_all_primes(N, S, P) : 
    all_prime_numbers_list = [] 
    # all primes less than S itself 
    for i in range(P, S) : 
        # if i is prime add it to prime vector 
        if is_prime(i): 
            all_prime_numbers_list.append(i) 
    # if primes are less than N 
    if (len(all_prime_numbers_list) < N): return
    print(all_prime_numbers_list) # to view all primes between P and S
    return find_N_sets_sums_S(all_prime_numbers_list, N, S) 


# Output all solutions that has N numbers that does not repeat each other or exceed S 
def find_N_sets_sums_S(array, N, S, results = None, sub_results = None):
    if results == None: results = []
    if sub_results == None: sub_results = []
    if sum(sub_results) > S or len(sub_results) > N: return
    if sum(sub_results) == S and len(sub_results) == N:
        results.append(sub_results)
    for i in range(len(array)):
        curr_item = array[i]
        remaining_items = array[i+1:]
        # Instead of backtracking, introduce new limitation to eliminate a branch of recursions to continue
        if remaining_items != None and curr_item not in sub_results: 
            find_N_sets_sums_S(remaining_items, N, S, results, sub_results + [curr_item])
    return results
    
    
S = 54
N = 4
P = 3
find_all_primes(N, S, P)

[3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53]


[[3, 5, 17, 29],
 [3, 7, 13, 31],
 [3, 11, 17, 23],
 [5, 7, 11, 31],
 [5, 7, 13, 29],
 [5, 7, 19, 23],
 [5, 13, 17, 19],
 [7, 11, 13, 23],
 [7, 11, 17, 19]]

In [2]:
# The version of the below permutation function will be used to solve N-Queen Problem
# Show permutations of n elements on an array, with repetitions of each element allowed with a stack (board array)

def permutations(n, board = None):
    if board == None: board = []
    if n == len(board): return 1
    count = 0 # count the possible permutations
    for col in range(n):
        board.append(col)
        count += permutations(n, board)
        if len(board) == n: # to view all solutions
            print('board:', board, 'count:', count)
        board.pop()
    return count # return total number of permutations of n elements

permutations(3)


board: [0, 0, 0] count: 1
board: [0, 0, 1] count: 2
board: [0, 0, 2] count: 3
board: [0, 1, 0] count: 1
board: [0, 1, 1] count: 2
board: [0, 1, 2] count: 3
board: [0, 2, 0] count: 1
board: [0, 2, 1] count: 2
board: [0, 2, 2] count: 3
board: [1, 0, 0] count: 1
board: [1, 0, 1] count: 2
board: [1, 0, 2] count: 3
board: [1, 1, 0] count: 1
board: [1, 1, 1] count: 2
board: [1, 1, 2] count: 3
board: [1, 2, 0] count: 1
board: [1, 2, 1] count: 2
board: [1, 2, 2] count: 3
board: [2, 0, 0] count: 1
board: [2, 0, 1] count: 2
board: [2, 0, 2] count: 3
board: [2, 1, 0] count: 1
board: [2, 1, 1] count: 2
board: [2, 1, 2] count: 3
board: [2, 2, 0] count: 1
board: [2, 2, 1] count: 2
board: [2, 2, 2] count: 3


27

In [3]:
# Alternatively a simple permutation function can be used

test_array = [0,1,2]
def permutations2(array, results = None, sub_results = None):
    if results == None: results = []
    if sub_results == None: sub_results = []
    if len(sub_results) > len(array): return 
    if len(sub_results) == len(array): results.append(sub_results)
    for i in range(len(array)):
        curr_element = array[i]
        permutations2(array, results, sub_results + [curr_element])
    return results
    
permutations2(test_array)

[[0, 0, 0],
 [0, 0, 1],
 [0, 0, 2],
 [0, 1, 0],
 [0, 1, 1],
 [0, 1, 2],
 [0, 2, 0],
 [0, 2, 1],
 [0, 2, 2],
 [1, 0, 0],
 [1, 0, 1],
 [1, 0, 2],
 [1, 1, 0],
 [1, 1, 1],
 [1, 1, 2],
 [1, 2, 0],
 [1, 2, 1],
 [1, 2, 2],
 [2, 0, 0],
 [2, 0, 1],
 [2, 0, 2],
 [2, 1, 0],
 [2, 1, 1],
 [2, 1, 2],
 [2, 2, 0],
 [2, 2, 1],
 [2, 2, 2]]

In [4]:
# Preparation for N-Queens Problem:

# No need for unnecessary iterations for the N-Queens problem's permutations. 
# Add another base case to the function above: No repetitions allowed - Backtracking

test_array = [0,1,2]
def permutations2(array, results = None, sub_results = None):
    if results == None: results = []
    if sub_results == None: sub_results = []
    if len(sub_results) > len(array): return 
    if len(sub_results) == len(array): results.append(sub_results)
    for i in range(len(array)):
        curr_element = array[i]
        if curr_element not in sub_results: # Backtracking
            permutations2(array, results, sub_results + [curr_element])
    return results
    
permutations2(test_array)

[[0, 1, 2], [0, 2, 1], [1, 0, 2], [1, 2, 0], [2, 0, 1], [2, 1, 0]]

In [5]:
# Find solutions to N-Queens Problem:

# Show all possiblities of N queens to be placed on a chess board with size N x N without attacking each other
# Board is an array representing n x n table where queens can be placed
# Ex: board = [1,3,0,2] , row 0 & col 1, row 1 & col 3, row 2 & col 0, and row 2 & col 3: total 4 queens

# 3-Step-Solution:

# 1- Find all permutations where a queen can be placed to one specific row and column, with no repetitions
# Queens can't attack each other if they are not in the same row or column which is:
# permutation of all indices of an array without repetition

import numpy as np
test_array = [0,1,2,3]
def N_queen_on_a_board_permutations(array, results = None, sub_results = None):
    if results == None: results = []
    if sub_results == None: sub_results = []
    if len(sub_results) > len(array): return 
    if len(sub_results) == len(array): results.append(sub_results)
    for i in range(len(array)):
        curr_element = array[i]
        if curr_element not in sub_results: # Backtracking
            permutations2(array, results, sub_results + [curr_element])
    return results

# all possible placements of N queens on a board "without repetition"
possible_queen_placements = N_queen_on_a_board_permutations(test_array)
# to view all possible placements where each queen is occupying one row & column:
# print(possible_queen_placements) 



# 2- Exclude all right diagonal placements of queens in the board
# Eliminate all the possible configurations that queens might see each other diagonally in //// direction: 
# Diagonal placements of queens seeing each other would be where: row + col = col + row

def boards_without_right_diagonal_conflict(all_possible_boards):
    boards_without_diagonal_conflict = []
    for curr_board in all_possible_boards:
        sum_list = []
        for row, col in enumerate(curr_board):
            sum_of_row_and_col = 0
            sum_of_row_and_col = row + col
            sum_list.append(sum_of_row_and_col)
            if len(set(sum_list)) == len(curr_board):
                boards_without_diagonal_conflict.append(curr_board)
    return boards_without_diagonal_conflict

list_without_right_diagonal_conflict = boards_without_right_diagonal_conflict(possible_queen_placements)
print(list_without_right_diagonal_conflict) # to view a solution set without diagonal conflict


# 3- Take the mirror image of all the results and then run the step 2 again to eliminate all 
# left diagonal placements of queens in the board

def create_mirror_images(boards):
    mirror_images_of_boards = []
    # create the mirror images of the boards:
    for board in boards:
        mirror_image = []
        for i in range(len(board)):
            mirror_image.insert(0, board[i])
        mirror_images_of_boards.append(mirror_image)
    return mirror_images_of_boards
    
    
mirror_image_list = create_mirror_images(list_without_right_diagonal_conflict)
# print(mirror_image_list)
all_images_without_diagonal_conflict = boards_without_right_diagonal_conflict(mirror_image_list)
# print(all_images_without_diagonal_conflict)


# Extra:
# Verify that queens are NOT neighbors, and there are N queens on a NxN table from a set of boards where
# the set of boards are all confirmed not having any queens diagonally and none share the same column or row. 

# Use the same algorithm of counting islands on a 2D array
# Create a 2D array for all solutions_of_no_diagonal_conflicts and do a dfs to count islands. 
# All queens should be isolated from each other. Or in other words, no queens should be adjacent to each other. 

def print_solutions(boards):
    # prepare the boards by putting n queens on an n x n board and check which boards would yield 4 islands. 
    for board in boards:
        n = len(board)
        two_D_board = np.zeros([n, n], dtype = int)
        for row, col in enumerate(board):
            two_D_board[row][col] = 1
        # print(two_D_board) to view the 2D array representation of the boards
        # count the number of islands, if they sum up to n, print the board
        if count_islands(two_D_board) == len(board):
            print(two_D_board)


def DFS(i, j, graph, visited, N, D):
    visited[i][j] = True
    for each_neighbor in [[-1, -1], [-1, 0], [-1, 1], [0, -1], [0, 1], [1, -1], [1, 0], [1, 1]]: 
        r , c = each_neighbor
        if (i + r) >= 0 and (i + r) < N and (j + c) >= 0 and (j + c) < D: # if within the borders of the matrix
            if graph[i+r][j+c] == 1 and visited[i+r][j+c] == 0: 
                DFS(i + r, j + c, graph, visited, N, D) 


def count_islands(graph): 
    N,D = graph.shape
    visited = np.zeros([N, D], dtype = int)
    count = 0
    for i in range(N): 
        for j in range(D): 
            if visited[i][j] == False and graph[i][j] == 1: 
                DFS(i, j, graph, visited, N, D) 
                count += 1
    return count


print_solutions(all_images_without_diagonal_conflict)



[[0, 1, 2, 3], [0, 2, 3, 1], [0, 3, 1, 2], [1, 2, 0, 3], [1, 3, 0, 2], [2, 0, 1, 3], [2, 0, 3, 1]]
[[0 0 1 0]
 [1 0 0 0]
 [0 0 0 1]
 [0 1 0 0]]
[[0 1 0 0]
 [0 0 0 1]
 [1 0 0 0]
 [0 0 1 0]]
