In [1]:
# Graph DFS Implimentations:

In [2]:
# Iterative DFS traversal from a given source vertex.  
# Exhausts all possible moves from the source vertex without visiting any vertices the second time.

test_graph = {0: [2, 3], 1: [0,4], 2:[1], 3: [] , 4:[]}

class Graph:  
    def __init__(self,graph):   
        self.graph = graph  
        self.visited = []
        self.stack = []

    def dfs(self, source_node):
        self.stack = [source_node]
        while len(self.stack) > 0:
            next_node = self.stack.pop() # pop the last item
            self.visited.append(next_node)
            print(next_node, end = ' ')
            for i in self.graph[next_node]:
                if i not in self.visited and i != None:
                    self.stack.append(i)
        
        
g = Graph(test_graph)
g.dfs(0)
        

0 3 2 1 4 

In [3]:
# Reminder of the differences of simple dfs and bfs:

test_graph = {0: [2, 3], 1: [0,4], 2:[1], 3: [] , 4:[]}

# do an iterative dfs with a stack
def iterative_dfs(test_graph, source_node):
    stack = [source_node]
    visited = []
    while len(stack) > 0:
        next_node = stack.pop() # pop the last item
        visited.append(next_node)
        for i in test_graph[next_node]:
            if i not in visited and i != None:
                stack.append(i)
    return visited        

print(iterative_dfs(test_graph, 2))


# do a dfs with recursion
def dfs_with_recursion(test_graph, source_node, stack = None, visited = None):
    if stack == None: stack = [source_node]
    if visited == None: visited = []
    if len(stack) > 0:
        next_node = stack.pop() # pop the last item
        visited.append(next_node)
        for i in test_graph[next_node]:
            if i not in visited and i != None:
                stack.append(i)
        dfs_with_recursion(test_graph, next_node, stack, visited)    
    return visited    

print(dfs_with_recursion(test_graph, 2))


# do an iterative bfs with a queue
def iterative_bfs(test_graph, source_node):
    queue = [source_node]
    visited = []
    while len(queue) > 0:
        next_node = queue.pop(0) # pop the first item
        visited.append(next_node)
        for i in test_graph[next_node]:
            if i not in queue and i not in visited and i != None:
                queue.append(i)
    return visited        
                
print(iterative_bfs(test_graph, 2))


# do a bfs with recursion
def bfs_with_recursion(test_graph, source_node, queue = None, visited = None):
    if queue == None: queue = [source_node]
    if visited == None: visited = []
    if len(queue) > 0:
        next_node = queue.pop(0) # pop the first item
        visited.append(next_node)
        for i in test_graph[next_node]:
            if i not in visited and i != None:
                queue.append(i)
        bfs_with_recursion(test_graph, next_node, queue, visited)    
    return visited    
    
        
print(bfs_with_recursion(test_graph, 2))



[2, 1, 4, 0, 3]
[2, 1, 4, 0, 3]
[2, 1, 0, 4, 3]
[2, 1, 0, 4, 3]


In [4]:
# show transitive closure on a 2D matrix with dfs

test_graph = {0: [1, 2], 1: [2], 2: [0, 3], 3: [3]}
import numpy as np

def dfs(u, v, visited, graph):
    visited[u][v] = 1
    for i in graph[v]: # traverse over the connections of the destination
        if i != None and visited[u][i] == 0: # if there has been no connection from u to i
            dfs(u, i, visited, graph)


def apply_tc(graph):
    n = len(graph)
    visited = np.zeros([n,n], dtype = int)
    for i in graph.keys():
        dfs(i, i, visited, graph)
    return visited # tc of the graph

apply_tc(test_graph)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [0, 0, 0, 1]])

In [5]:
# checking cycles in a graph traditionally is done with bfs and not dfs:

test_graph = {0: [1], 1: [3, 6], 2: [4, 5], 3: [2], 4: [0], 5: [], 6: []}

def iterative_bfs(graph, source): 
    visited = []
    queue = [source]
    while len(queue) > 0:
        curr_node = queue.pop(0) # last item is popped
        visited.append(curr_node)
        for each_conn in graph[curr_node]:
            if each_conn != None and each_conn not in visited:
                queue.append(each_conn)
            elif each_conn in visited:
                print('cycle')
    return visited

iterative_bfs(test_graph, 0)

cycle


[0, 1, 3, 6, 2, 4, 5]

In [6]:
# Finding cycles in an undirected graph

# Detect if there is any cycles in an undirected graph where connections can be seen once
test_graph_cycle = {0: [1], 1: [3, 6], 2: [4, 5], 3: [2], 4: [0], 5: [], 6: []} # 2--4--0 cycle is added

class Graph: 
    def __init__(self, graph): 
        self.graph = graph # default dictionary to store graph in adj list format
        self.parent = np.arange(0, len(self.graph))
         
            
    def is_cyclic(self):  
        for k,v in self.graph.items(): 
            for each_value in v: 
                x = self.find_parent(k)  
                y = self.find_parent(each_value) 
                if x == y: 
                    print('graph contains cyclic connection')
                    return True 
                else: # union them (assign the item's parent in the value to the key's parent)
                    self.parent[y] = x 
            # print(self.parent) # to view how the parent index is changing
    
    def find_parent(self, i): # reach to the parent with a dfs
        if self.parent[i] != i: # has no parent return the index
            return self.find_parent(self.parent[i])
        else: # has a parent return the parent's index
            return self.parent[i] 
  

    
# Create a graph given in the above diagram 
g = Graph(test_graph_cycle) 
# test the class
print(g.is_cyclic())
# view the parent list after all vertices are seen
print(g.parent)

graph contains cyclic connection
True
[0 0 0 0 2 2 0]


In [7]:
# Apply path compression and union by rank method on a directed graph and detect cycles
# Prepare a test set as a dictionary view of an acyclic undirected graph where connections seen once

test_conn = test_graph_cycle = {0: [1], 1: [3, 6], 2: [4, 5], 3: [2], 4: [], 5: [], 6: []}
    
class Graph2():
    def __init__(self, graph):
        self.graph = graph 
        self.parent = np.arange(0, len(graph)) # initialize the parent of the vertex to itself 
        self.rank = np.zeros(len(graph)) # all ranks start from zero for each vertex
                
        
    def is_graph_cyclic(self):
        for k,v in self.graph.items(): # for each vertex
            k_parent = self.find_parent(k)
            for j in v: # for each connection of each vertex
                j_parent = self.find_parent(j)
                if k_parent == j_parent:
                    return True
                else:
                    self.union(k_parent, j_parent)
        
        
    def find_parent(self, vertex): # a simple dfs
        if self.parent[vertex] != vertex:
            self.parent[vertex] = self.find_parent(self.parent[vertex])
        return self.parent[vertex]
             
    
    def union(self, u, v): # path compression and union by rank 
        if self.rank[u] > self.rank[v]:
            self.parent[v] = u
        elif self.rank[u] < self.rank[v]:
            self.parent[u] = v
        else: # if the ranks are the same
            self.parent[v] = u
            self.rank[u] += 1
            

            
gtest = Graph2(test_conn)
print(gtest.is_graph_cyclic())
# view the parent and rank after all vertices are visited
print(gtest.parent, gtest.rank)

None
[0 0 0 0 0 0 0] [2. 0. 1. 0. 0. 0. 0.]


In [8]:
# Find the number of islands assuming 1s are connected to each other forming an island among sea of zeros
# Complexity: O(N x D)

import numpy as np
class Graph: 
  
    def __init__(self, g): # g is a 2D matrix with random boolean numbers
        self.N, self.D = g.shape
        self.graph = g 
  

    def within_borders(self, i, j, visited): 
        # returns true if: i and j are within the boundaries, vertex hasn't been visited, and graph[i][j] is 1 
        return (i >= 0 and i < self.N and j >= 0 and j < self.D and visited[i][j] == False \
                and self.graph[i][j] == True) 
              
        
    def all_possible_moves(self): # simple permutation to obtain all moves to the neighboring cells
        array = [-1,0,1] # all possible moves for either i or j if it starts from 0
        k = 2
        return self._all_possible_moves(array, k)
        
        
    def _all_possible_moves(self, array, k, sub_array = None, result = None): 
        if result == None: result = []
        if sub_array == None: sub_array = []
        if len(sub_array) == k: 
            result.append(sub_array)
            return
        for i in range(len(array)):
            self._all_possible_moves(array, k, sub_array + [array[i]], result)
        return [i for i in result if i != [0,0]] # eliminate the possibility of not moving at all for both indices
        
    
    def store_all_possible_moves(self):
        self.row_col_neighbors = self.all_possible_moves() # all possible moves of i and j can take together
        
        
    def DFS(self, i, j, visited): 
        # row_col_neighbors is simply: [[-1, -1], [-1, 0], [-1, 1], [0, -1], [0, 1], [1, -1], [1, 0], [1, 1]] 
        visited[i][j] = True
        for k in self.row_col_neighbors: 
            r , c = k
            if self.within_borders(i + r, j + c, visited) == True: 
                self.DFS(i + r, j + c, visited) 
  

    def count_islands(self): 
        self.store_all_possible_moves()
        visited = np.zeros([self.N,self.D], dtype = int)
        count = 0
        for i in range(self.N): 
            for j in range(self.D): 
                if visited[i][j] == False and self.graph[i][j] == 1: 
                    self.DFS(i, j, visited) 
                    count += 1
                    
        
        print(visited, '\n' , (visited == graph).all()) # visited should just look like the original graph
        return count 
  
  
graph = np.array([[1, 1, 1, 0, 0], 
                  [0, 1, 0, 0, 1], 
                  [1, 0, 0, 1, 1], 
                  [0, 0, 0, 0, 1], 
                  [1, 0, 1, 0, 1]])

test_graph = Graph(graph)
test_graph.count_islands()

[[1 1 1 0 0]
 [0 1 0 0 1]
 [1 0 0 1 1]
 [0 0 0 0 1]
 [1 0 1 0 1]] 
 True


4

In [9]:
# count number of islands with only 2 functions 

test_graph = np.array([[0, 1, 1, 0, 0], 
                       [0, 1, 0, 0, 1], 
                       [1, 0, 0, 1, 1], 
                       [0, 0, 0, 0, 1], 
                       [1, 0, 1, 0, 1]])

    
def DFS(i, j, graph, visited, N, D):
    visited[i][j] = True
    for each_neighbor in [[-1, -1], [-1, 0], [-1, 1], [0, -1], [0, 1], [1, -1], [1, 0], [1, 1]]: 
        r , c = each_neighbor
        if (i + r) >= 0 and (i + r) < N and (j + c) >= 0 and (j + c) < D: # if within the borders of the matrix
            if graph[i+r][j+c] == 1 and visited[i+r][j+c] == 0: 
                DFS(i + r, j + c, graph, visited, N, D) 


def count_islands(graph): 
    N,D = graph.shape
    visited = np.zeros([N, D], dtype = int)
    count = 0
    for i in range(N): 
        for j in range(D): 
            if visited[i][j] == False and graph[i][j] == 1: 
                DFS(i, j, graph, visited, N, D) 
                count += 1
    return visited , count


count_islands(test_graph)

(array([[0, 1, 1, 0, 0],
        [0, 1, 0, 0, 1],
        [1, 0, 0, 1, 1],
        [0, 0, 0, 0, 1],
        [1, 0, 1, 0, 1]]), 4)

In [10]:
# Python3 program to find the longest cable length between any two cities with Time Complexity : O(V * (V + E))

# There 6 cities index from [0 to 5]. The distance from index 0 to index 1 is 3, the distance from index 1 to 5 is 2..
# Here is the visual of the cities and their distances

# 0 --- 1 ---- 2
#       1 -- 5 ------ 3
#            5 ----- 4

# matrix representation of an undirected test graph 
graph = np.array([[0,3,0,0,0,0], 
                  [3,0,4,0,0,2],
                  [0,4,0,0,0,0],
                  [0,0,0,0,0,6],
                  [0,0,0,0,0,5],
                  [0,2,0,6,5,0]])

import numpy as np
def DFS(graph, src, prev_len, max_len, visited, results): 
    
    visited[src] = True
    curr_len = 0
    for i in range(len(graph[src])): # for all connections of the source
        if graph[src][i] != 0 and visited[i] == False:
            each_conn = graph[src][i]
            curr_len = prev_len + each_conn 
            if max_len < curr_len:  
                max_len = curr_len 
            DFS(graph, i, curr_len,  max_len, visited, results) 
        results.append(max_len)

        
def longest_distance(graph): 
    
    results = []
    max_len = -np.inf
    for i in range(len(graph)): 
        visited = [False] * len(graph)  
        DFS(graph, i, 0, max_len, visited, results) 
  
    return max(results) 


longest_distance(graph)


12

In [11]:
# Find a Mother Vertex in a Directed and Connected Graph 
# Mother Vertex: A vertex v such that all other vertices in graph can be reached by a path from v

# Undirected Connected Graphs or Disconnected Graphs can't have a mother vertex. 
test_graph = {0: [1, 2], 1: [3], 2: [], 3:[], 4: [1],  5: [6, 2], 6: [4, 0]}

class Graph:   
    def __init__(self, graph): 
        self.graph = {0: [1, 2], 1: [3], 2: [], 3:[], 4: [1],  5: [6, 2], 6: [4, 0]} # connections

    # Do DFS traversal from the specified vertex of the given graph.
    # If there is a mother vertex, then a dfs from mother vertex should reach out to all vertices
    def DFS(self, k, visited): 
        visited[k] = True
        for v in self.graph[k]: # for each connection 
            if v != None and visited[v] == False: 
                self.DFS(v, visited) # visited value becomes the new key for each recursion
        return visited
            
        
    def find_mother_vertex(self): 
        for i in range(len(self.graph)): 
            visited = [False]*(len(self.graph)) 
            result = self.DFS(i,visited) 
            # print(i, result) to view the visited vertices by dfs made from each vertex
            if result == [True] * len(self.graph):
                return i

g = Graph(test_graph)  
print(g.find_mother_vertex()) 

5


In [12]:
# Python program to print all different paths from a source vertex to a destination vertex with dfs

import numpy as np
test_graph = {0: [1, 3], 1: [3], 2: [0,1], 3:[]}
visited = [False] * len(test_graph)
import copy

def print_all_paths_from_s_to_d(graph, s, d, visited, path = None, result = None):
    if result == None: result = []
    if path == None: path = []
    visited[s] = True
    path.append(s) 
    if s == d: 
        sub_result = copy.deepcopy(path)
        result.append(sub_result)
    for i in graph[s]: 
        if visited[i] == False: 
            print_all_paths_from_s_to_d(graph, i, d, visited, path, result) 
    path.pop() # pop the last item reached and mark it as unvisited
    visited[s] = False # reassign the current node to False to go back and find another route
    return result

print_all_paths_from_s_to_d(test_graph, 2, 3, visited) 

[[2, 0, 1, 3], [2, 0, 3], [2, 1, 3]]