 #### First Part: Greedy MST Algorithms -  Kruskal's & Prim's

In [1]:
# Implimentation of Prims: O(Elog V), KRUSKAL: (E*logE) for finding MST in an undirected graph
# create an undirected graph in matrix form (where a---b == b---a)

import numpy as np
size = 10
undirected_graph_matrix = np.zeros([size, size])
probability_set = [0.5, 0.05, 0.1, 0.1, 0.03, 0.03, 0.03, 0.01, 0.1, 0.05]
vertex_list = np.arange(0,10)
for i in range(size): # each vertex
    for j in range(size): # immediate connections of each vertex
        random_weight = np.random.choice(vertex_list, p = probability_set)
        undirected_graph_matrix[i][j] = random_weight
        undirected_graph_matrix[j][i] = random_weight
        if i == j:
            undirected_graph_matrix[i][j] = 0   
print('undirected graph')
print(undirected_graph_matrix, '\n')   

undirected graph
[[0. 2. 8. 0. 3. 0. 0. 3. 9. 1.]
 [2. 0. 2. 3. 3. 0. 3. 0. 3. 0.]
 [8. 2. 0. 0. 0. 3. 0. 0. 0. 8.]
 [0. 3. 0. 0. 3. 8. 0. 3. 0. 3.]
 [3. 3. 0. 3. 0. 0. 7. 0. 0. 0.]
 [0. 0. 3. 8. 0. 0. 8. 2. 6. 3.]
 [0. 3. 0. 0. 7. 8. 0. 2. 3. 0.]
 [3. 0. 0. 3. 0. 2. 2. 0. 2. 0.]
 [9. 3. 0. 0. 0. 6. 3. 2. 0. 7.]
 [1. 0. 8. 3. 0. 3. 0. 0. 7. 0.]] 



In [2]:
# represent the matrix connection as an adjacency list

test_matrix = undirected_graph_matrix
adj_list = []
for i in range(len(test_matrix)):
    for j in range(len(test_matrix[i])):
        if i != j and test_matrix[i][j] != 0:
            adj_list.append([i,j, test_matrix[i][j]]) # the representation is source, target, weight as u, v, w
print(sorted(adj_list, key = lambda x: x[2]))

# view thnumber of vertices:
V = list(set([i[0] for i in adj_list] + [i[1] for i in adj_list]))
print('vertices:', V)

[[0, 9, 1.0], [9, 0, 1.0], [0, 1, 2.0], [1, 0, 2.0], [1, 2, 2.0], [2, 1, 2.0], [5, 7, 2.0], [6, 7, 2.0], [7, 5, 2.0], [7, 6, 2.0], [7, 8, 2.0], [8, 7, 2.0], [0, 4, 3.0], [0, 7, 3.0], [1, 3, 3.0], [1, 4, 3.0], [1, 6, 3.0], [1, 8, 3.0], [2, 5, 3.0], [3, 1, 3.0], [3, 4, 3.0], [3, 7, 3.0], [3, 9, 3.0], [4, 0, 3.0], [4, 1, 3.0], [4, 3, 3.0], [5, 2, 3.0], [5, 9, 3.0], [6, 1, 3.0], [6, 8, 3.0], [7, 0, 3.0], [7, 3, 3.0], [8, 1, 3.0], [8, 6, 3.0], [9, 3, 3.0], [9, 5, 3.0], [5, 8, 6.0], [8, 5, 6.0], [4, 6, 7.0], [6, 4, 7.0], [8, 9, 7.0], [9, 8, 7.0], [0, 2, 8.0], [2, 0, 8.0], [2, 9, 8.0], [3, 5, 8.0], [5, 3, 8.0], [5, 6, 8.0], [6, 5, 8.0], [9, 2, 8.0], [0, 8, 9.0], [8, 0, 9.0]]
vertices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [3]:
# Write Kruskal's Algorithm to find the MST of a given adjacency list representation of an undirected graph 

test_adj_list = [[0, 5, 1.0], [5, 0, 1.0], [1, 7, 2.0], [2, 6, 2.0], [2, 7, 2.0], [6, 2, 2.0], [7, 1, 2.0], 
                 [7, 2, 2.0], [0, 6, 3.0], [1, 4, 3.0], [3, 9, 3.0], [4, 1, 3.0], [4, 5, 3.0], [4, 8, 3.0], 
                 [5, 4, 3.0], [5, 6, 3.0], [6, 0, 3.0], [6, 5, 3.0], [8, 4, 3.0], [9, 3, 3.0], [0, 2, 4.0], 
                 [2, 0, 4.0], [5, 7, 4.0], [7, 5, 4.0], [0, 3, 5.0], [3, 0, 5.0], [0, 9, 8.0], [2, 8, 8.0], 
                 [3, 4, 8.0], [4, 3, 8.0], [8, 2, 8.0], [9, 0, 8.0], [5, 8, 9.0], [8, 5, 9.0]]

import numpy as np

class Kruskals:
    def __init__(self, adj_list):
        self.adj_list = sorted(adj_list, key = lambda item : item[2]) 
        self.vertices = set([i[0] for i in adj_list] + [i[1] for i in adj_list]) # 0 to 9 all the vertices
        self.parent = np.arange(len(self.vertices))
        self.rank = np.zeros(len(self.vertices))
        
    
    def find_parent(self, u):
        if self.parent[u] != u:
            return self.find_parent(self.parent[u])
        else:
            return u
            
        
    def union_by_rank(self, u, v):
        if self.rank[u] > self.rank[v]:
            self.parent[v] = u
        elif self.rank[u] < self.rank[v]:
            self.parent[u] = v
        else:
            self.parent[v] = u
            self.rank[u] += 1
            
    def MST(self):
        i = 0
        self.MST_list = []
        while len(self.MST_list) < len(self.vertices)-1 and i < len(self.adj_list):
            u, v, w = self.adj_list[i]
            parent_u = self.find_parent(u)
            parent_v = self.find_parent(v)
            if parent_u != parent_v:
                self.MST_list.append(self.adj_list[i])
                self.union_by_rank(parent_u,parent_v)
            i += 1
        return self.MST_list
        
        
test_kruskals = Kruskals(test_adj_list)
results = test_kruskals.MST()
# print(test_kruskals.parent, test_kruskals.rank)
# print(results)
spt = sum([i[2] for i in results])
print(spt)
%timeit Kruskals(test_adj_list)
print(results)

24.0
10.5 µs ± 520 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
[[0, 5, 1.0], [1, 7, 2.0], [2, 6, 2.0], [2, 7, 2.0], [0, 6, 3.0], [1, 4, 3.0], [3, 9, 3.0], [4, 8, 3.0], [0, 3, 5.0]]


In [4]:
# Write Prim's Algorithm to find the MST of a given adjacency list representation of an undirected graph 

def prims_MST(vertex, adj_list): 
    vertices = set([i[0] for i in adj_list] + [i[1] for i in adj_list])
    # initialize empty edges array and empty MST
    MST = []
    edges = []
    visited = [vertex]

    # run prims algorithm until we create an MST that contains every vertex from the graph
    while len(MST) < len(vertices) - 1:
        # add each edge to list of potential edges
        for r in range(len(adj_list)): # this loop will only append the current vertex's connections. 
            edge = adj_list[r]
            if edge[0] == vertex and edge[2] != 0:
                edges.append(edge)
        # find edge with the smallest weight to a vertex that has not yet been visited
        minEdge = [None,None,np.inf]
        for e in range(0, len(edges)):
            if edges[e][2] < minEdge[2] and edges[e][1] not in visited:
                minEdge = edges[e]
                vertex = edges[e][1]
        # mark this vertex as visited
        visited.append(vertex)
        # push min edge to MST
        MST.append(minEdge)
        # remove the used edge from the edges list
        # edges.remove(minEdge) # unhash this line if the data is very large 
        
    return MST 
  
# pass the # of vertices and the graph to run prims algorithm 
%timeit prims_MST(0, test_adj_list)
result = prims_MST(0, test_adj_list)
spt = sum([i[2] for i in result])
print(spt)
print(result)

67.8 µs ± 574 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
24.0
[[0, 5, 1.0], [0, 6, 3.0], [6, 2, 2.0], [2, 7, 2.0], [7, 1, 2.0], [5, 4, 3.0], [4, 8, 3.0], [0, 3, 5.0], [3, 9, 3.0]]


#### Second Part: SPT Algoritms - Dijikstra & Bellman-Ford

In [5]:
# create a random directed graph with positive connection values

import numpy as np
np.random.seed(0)
def test_graph(n): # n vertices
    test_graph_set = np.random.rand(n,n)*100
    # 0 the source so that the node is acyclic to itself 
    for i in range(n):
        test_graph_set[i][i] = np.inf
        # test_graph_set[i][:i] = np.inf  # unmark if a tree structure is needed
    test_graph_set = np.around(test_graph_set, decimals = 2)
    return test_graph_set

test_set = test_graph(10) 
print(test_set[:10][:10])


[[  inf 71.52 60.28 54.49 42.37 64.59 43.76 89.18 96.37 38.34]
 [79.17   inf 56.8  92.56  7.1   8.71  2.02 83.26 77.82 87.  ]
 [97.86 79.92   inf 78.05 11.83 63.99 14.34 94.47 52.18 41.47]
 [26.46 77.42 45.62   inf  1.88 61.76 61.21 61.69 94.37 68.18]
 [35.95 43.7  69.76  6.02   inf 67.06 21.04 12.89 31.54 36.37]
 [57.02 43.86 98.84 10.2  20.89   inf 65.31 25.33 46.63 24.44]
 [15.9  11.04 65.63 13.82 19.66 36.87   inf  9.71 83.79  9.61]
 [97.65 46.87 97.68 60.48 73.93  3.92 28.28   inf 29.61 11.87]
 [31.8  41.43  6.41 69.25 56.66 26.54 52.32  9.39   inf 92.93]
 [31.86 66.74 13.18 71.63 28.94 18.32 58.65  2.01 82.89   inf]]


In [6]:
# write a naive DIJKSTRA's algorithm to find the SPT from a source vertex to all other vertices (O(v**2))

def graph_traverse_DJ_path(graph, source): 
    distance_list = [np.inf] * len(graph)
    visited_vertices_list = [False] * len(graph)
    distance_list[source] = 0
    for each_vertex in range(len(graph)):
        min_value = np.inf
        for i in range(len(distance_list)):
            if distance_list[i] < min_value and visited_vertices_list[i] == False:
                min_value = distance_list[i]
                min_at_index = i
        visited_vertices_list[min_at_index] = True
        # print(min_at_index, visited_vertices_list) to view the order of vertices visited
        for i in range(len(distance_list)):
            if visited_vertices_list[i] == False and graph[min_at_index][i] > 0 and \
            distance_list[min_at_index] + graph[min_at_index][i] < distance_list[i]: 
                distance_list[i] = distance_list[min_at_index] + graph[min_at_index][i]
    return np.around(distance_list, decimals = 2)

print(graph_traverse_DJ_path(test_set, 0))
%timeit graph_traverse_DJ_path(test_set, 0)

[ 0.   54.8  51.52 48.39 42.37 44.27 43.76 40.35 69.96 38.34]
103 µs ± 6.55 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [7]:
import numpy as np
# turn the matrix into an adjacency list
adj_list = [[i, u, test_set[i][u]] for i in range(len(test_set)) for u in range(len(test_set))] 
# view the adjacency list
print(adj_list[5:15])

[[0, 5, 64.59], [0, 6, 43.76], [0, 7, 89.18], [0, 8, 96.37], [0, 9, 38.34], [1, 0, 79.17], [1, 1, inf], [1, 2, 56.8], [1, 3, 92.56], [1, 4, 7.1]]


In [8]:
# Bellman-Ford Algorithm to traverse the test graph to find the SPT

def graph_bellman_ford(adj_list, source): 
    vertices = set([i[0] for i in adj_list] + [i[1] for i in adj_list])
    # Initialize distances list from source vertex to other vertices
    dist = [np.inf] * len(vertices)
    # Make it acyclic to itself
    dist[source] = 0 
    # Loop over V-1 times and update the distance list where V is the number of vertices of the test_set (matrix)
    for i in range(len(vertices) - 1): 
        for u, v, w in adj_list: 
            if dist[u] != np.inf and w != 0 and dist[u] + w < dist[v]: 
                dist[v] = dist[u] + w 

    # Check for negative-weight cycles going over it one more time to see if there is any update.  
    for u, v, w in adj_list: 
        if dist[u] != np.inf and w != 0 and dist[u] + w < dist[v]: 
            print ("Graph contains negative weight cycle")
            return
    
    return np.around(dist, decimals = 2)
        
print(graph_bellman_ford(adj_list, 0)) 
# compare naive djikstra, improved djikstra, and bellman-ford
%timeit graph_bellman_ford(adj_list, 0) 


[ 0.   54.8  51.52 48.39 42.37 44.27 43.76 40.35 69.96 38.34]
694 µs ± 33.1 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [9]:
# Bonus: find the shortest path with exactly k edges from s to d with Time complexity: O(E*K)

import numpy as np
test_matrix = np.array([[0,10,3,2],
                        [0,0,0,7],
                        [0,0,0,6],
                        [0,0,0,0]])

adj_list =[[0, 1, 10], [0, 2, 3], [0, 3, 2], [1, 3, 7], [2, 3, 6]] 

def shortest_path_in_k_steps(s, d, adj_list, k): # 0,1,2,3 total 4 vertices
    vertices = set([i[0] for i in adj_list] + [i[1] for i in adj_list]) # all source and destination vertices
    # print(vertices) # to view all vertices
    distances = [np.inf] * (len(vertices)+1) # initialize the final distance array
    distances[s] = 0 # initialize distance from source to source as 0
    for i in range(k): # for the number of steps 
        dist1 = [np.inf] * len(distances) # reset distances achieved after each iteration
        for each_conn in adj_list: 
            u, v, w = each_conn
            if dist1[v] > distances[u] + w:
                dist1[v] = distances[u] + w
        # copy the best paths to distances array
        distances = dist1
        # print(distances) # to view the current distances 
    return distances[d]

shortest_path_in_k_steps(0, 3, adj_list, 2)


9