In [1]:
# Hashing Implimentations for Coding Interviews

In [2]:
# Sorting elements by their frequency 
# Example  Input: [9, 5, 9, 1, 5, 5, 6, 1, 1, 1]  Output: [1, 1, 1, 1, 5, 5, 5, 9, 9, 6]

def sort_by_freq(array):
    a_dict = {}
    for i in array:
        if i in a_dict.keys():
            a_dict[i] += 1
        else:
            a_dict[i] = 1
    print(a_dict) # to view
    sorted_dict_by_val = sorted(a_dict.items(), key = lambda x: x[1])
    print(sorted_dict_by_val)
    output = []
    for i in range(len(sorted_dict_by_val)):
        each_tuple = sorted_dict_by_val[i]
        k, v = each_tuple
        for j in range(v):
            output.insert(0, k)

    return output
    
test_array = [9, 5, 9, 1, 5, 5, 6, 1, 1, 1]
sort_by_freq(test_array)

{9: 2, 5: 3, 1: 4, 6: 1}
[(6, 1), (9, 2), (5, 3), (1, 4)]


[1, 1, 1, 1, 5, 5, 5, 9, 9, 6]

In [3]:
# longest sub-array with 0 sum
# input: [3, 9, 5, -9, -5, 5, 6, 1, -1, 1]  output: [9,5,-9,-5]

def longest_sub_array_w_0_sum(array):
    if len(array) == 0: return
    if len(array) == 1: return array
    # calculate the sum starting from first index and check if that sum is seen twice
    # mark the longest one and return the items of the longest sub-array with zero sum
    sum_array = []
    total = 0
    longest = 0
    for i in range(len(array)):
        total += array[i]
        sum_array.append(total)
        if total in sum_array:
            mark_seen_first = sum_array.index(total) 
            mark_seen_second = i
            length = mark_seen_second - mark_seen_first
            if length > longest:
                longest = length
                mark_longest_start = mark_seen_first
                mark_longest_end = mark_seen_second
    return array[mark_longest_start+1 : mark_longest_end+1]
    
longest_sub_array_w_0_sum([3, 9, 5, -9, -5, 5, 6, 1, -1, 1]) 
    
    
    

[9, 5, -9, -5]

In [4]:
# find common elements in 3 sorted array

arr1 = [1, 5, 10, 20, 40, 80]
arr2 = [6, 7, 20, 80, 100]
arr3 = [3, 4, 15, 20, 30, 70, 80, 120]

def common_elements(arr1,arr2,arr3):
    n = len(arr1)
    m = len(arr2)
    p = len(arr3)
    i, j, k = 0, 0, 0
    common_elements_array = []
    while i < n and j < m and k < p:
        if arr1[i] == arr2[j] == arr3[k]:
            common_elements_array.append(arr1[i])
            i += 1
            j += 1
            k += 1
        # find the array with the minimum element and move the index up by one
        elif arr1[i] < arr2[j] and arr1[i] < arr3[k]:
            i += 1
        elif arr2[j] < arr1[i] and arr2[j] < arr3[k]:
            j += 1
        else:
            k += 1
        
    return common_elements_array    
    
print(common_elements(arr1,arr2,arr3))
        
    
# do it by storing in a dictionary:

a_dict = {}
n = len(arr1)
m = len(arr2)
p = len(arr3)
i, j, k = 0, 0, 0
while i < n and j < m and k < p:
    if arr1[i] == arr2[j] == arr3[k]:
        a_dict[arr1[i]] = 'common'
        i += 1
        j += 1
        k += 1
    else:
        if arr1[i] < arr2[j] and arr1[i] < arr3[k]:
            i += 1
        elif arr2[j] < arr1[i] and arr2[j] < arr3[k]:
            j += 1
        else:
            k += 1 

print(a_dict.items())
        


[20, 80]
dict_items([(20, 'common'), (80, 'common')])


In [5]:
# A sorting based solution to print all combination of 4 elements in A[] with sum equal to X.  
# Naive solution is O**4 and hasining solution is O**2

# Naive
test_array = [10, 2, 3, 4, 5, 9, 7, 8] 
test_target = 23
def find_4_elements_equal_to_target(array, target): 
    n = len(array)
    results = []
    for i in range(0,n-3): 
        for j in range(i+1,n-2): 
            for k in range(j+1,n-1): 
                for l in range(k+1,n): 
                    if array[i] + array[j] + array[k] + array[l] == target:
                        results.append([array[i], array[j], array[k], array[l]])
    return results

print(find_4_elements_equal_to_target(test_array, test_target))


# Hashing solutions (ATTN: there are some repetitions and missing solutions in the results)
def find_4_elements_equal_to_target_with_hashing(array, target):  
    n = len(array)
    a_dict = {}
    results = []
    for i in range(len(array)):
        for j in range(i, len(array)):
            sum_of_two = array[i] + array[j]
            if target-sum_of_two in a_dict.keys():
                remaining_indices = a_dict[target-sum_of_two]
                if i not in remaining_indices and j not in remaining_indices and i != j and \
                                                                remaining_indices[0] != remaining_indices[1]:
                    results.append([array[i],array[j], array[remaining_indices[0]], array[remaining_indices[1]]]) 
            else:
                a_dict[sum_of_two] = (i,j)
            
    return results 

print(find_4_elements_equal_to_target_with_hashing(test_array, test_target))


[[10, 2, 3, 8], [10, 2, 4, 7], [2, 4, 9, 8], [2, 5, 9, 7], [3, 4, 9, 7], [3, 5, 7, 8]]
[[2, 3, 10, 8], [2, 4, 10, 7], [2, 7, 10, 4], [2, 8, 10, 3], [4, 7, 3, 9], [9, 7, 3, 4]]


In [6]:
# Find a pair of elements to swap between two arrays, so that the sum of two arrays are going to be the same

# Naive solution O(n*m):
def findswapitems(A,B): 
    # Calculation if sums from both lists 
    sum1=sum(A) 
    sum2=sum(B)
    for i in A: 
        for j in B: 
            newsum1=sum1-i+j 
            newsum2=sum2-j+i   
            if newsum1 == newsum2: 
                return i, j

test_a = [4,1,2,1,1,2] 
test_b = [3,6,3,3]
print(sum(test_a) , sum(test_b)) # move 6 in B to A and move 4 in A to B 
print(findswapitems(test_a , test_b))

# Better solution (O(nlog(n) + mlog(m))):
def findswapitems2(A,B): 
    # check if it is swappable
    sum1 = sum(A)
    sum2 = sum(B)
    target = (sum1 - sum2)/2
    A.sort() 
    B.sort() 
    i,j=0,0
    while(i<len(A) and j<len(B)): 
        diff = A[i]-B[j] 
        if diff == target: 
            return A[i], B[j] 
        elif diff <target: 
            i+=1
        else: 
            j+=1

print(findswapitems2(test_a,test_b))

# Best Solution with Hashing O(m+n):
def findswapitems3(A,B):
    sum_a = sum(A)
    sum_b = sum(B)
    # normally it is better to take the smaller array to create a dictionary 
    a_dict = {}
    for i in A:
        a_dict[i] = 'A'
    diff = (sum_a - sum_b)/2
    for i in range(len(B)):
        value_to_search = int(B[i] + diff)
        if value_to_search in a_dict.keys():
            return value_to_search , B[i]
        

print(findswapitems3(test_a, test_b))


11 15
(4, 6)
(1, 3)
(1, 3)


In [7]:
# Count distinct elements in every window of size k, sliding it from left to right

def count_distinct_elements(arr, k): 
    # find the number of items seen for each item in the window of length k, starting from index 0
    total_unique_items = []
    n = len(arr)
    mp = {}
    dist_count = 0
    for i in range(k): 
        if arr[i] in mp:
            mp[arr[i]] += 1 
        else:
            mp[arr[i]] = 1
      
    current_unique_items = len(mp)
    total_unique_items.append(current_unique_items)
    
    # Traverse through the remaining array 
    # add or increase the value of the new item and remove or decrease the value of the old item
    for i in range(k, n): 
        # slide the window to right for one step:
        # remove the old element from dictionary if it is only seen once so far
        n = mp.get(arr[i-k])
        if n == 1:
            del mp[arr[i-k]]
        # if old element has been seen a few times in the window k, then lower its value
        if n > 1:
            mp[arr[i-k]] -= 1

        # add the new element if it has not been seen before
        if arr[i] not in mp.keys():
            mp[arr[i]] = 1
        # increase the value of the new element since it is seen before
        else:
            mp[arr[i]] += 1
        
        total_unique_items.append(len(mp)) 

    return total_unique_items        
            
test_arr = [1, 2, 1, 3, 4, 2, 3] 
k = 4
count_distinct_elements(test_arr,k) 

[3, 4, 4, 3]

In [8]:
# Count the number of pairs in array whose sum is divisible by k

def number_of_sum_of_pairs_div_by_K(array, k):
    n = len(array)
    hash_table = {}
    sum_of_pairs_div_by_k = 0
    
    # store the remainder of each item in the array to the hash table with keys in mod k
    for i in array:
        rem = i % k
        if rem in hash_table.keys():
            hash_table[rem] += 1
        else:
            hash_table[rem] = 1
            
    # if k is even, check out the number of items that yield k/2, then sum up all those pairs
    if k % 2 == 0: 
        mid_k = hash_table.get(k//2) // 2
        sum_of_pairs_div_by_k += mid_k
        
    # add the pairs that are already divisable by k (all pairs at zero remainder)
    if hash_table.get(0) != None:
        zero_remainder_items = hash_table.get(0) // 2
        sum_of_pairs_div_by_k += zero_remainder_items
    
    # starting from index 1 to index k-1 and moving to the middle, find out how many matches can be made by
    # sum up the multiplication of the number of items in the both sides of the array until reaching the middle index
    i = 1
    j = len(hash_table) -1
    while i <= j:
        if hash_table.get(i) != None and hash_table.get(j) != None:
            number_of_items_at_i = hash_table.get(i)
            number_of_items_at_j = hash_table.get(j)
            combinations_of_two = number_of_items_at_i * number_of_items_at_j
            sum_of_pairs_div_by_k += combinations_of_two
            i += 1
            j -= 1
        
    return sum_of_pairs_div_by_k

test_array = [2, 2, 1, 7, 5, 3] 
number_of_sum_of_pairs_div_by_K(test_array, 4)   
    
    

5

In [9]:
# Find longest consecutive subsequence in an array

import numpy as np
test_array = [1, 9, 3, 10, 4, 20, 2] # answer: 4 with numbers 1,2,3,4

# Naive method:
def lcsubs(array):
    sorted_array = np.sort(array)
    longest_cons_subs = 1
    length = 1 
    for i in range(1, len(sorted_array)):
        if sorted_array[i] == 1 + sorted_array[i-1]:
            length += 1
            if length > longest_cons_subs:
                longest_cons_subs = length
        else:
            length = 0
    return longest_cons_subs

print(lcsubs(test_array))
            

# Hashing method:
def longest_cons_subs(array):
    n = len(array)
    s = set() 
    max_length = 0
    length = 0
    
    # Hash all the array elements into a set
    for each_item in array: 
        s.add(each_item) 
        
    # go over each element, find the starting element, reset the length, check each item coming after that element
    for i in range(n): 
        if (array[i]-1) not in s: # to find the starting element array[i], confirm if array[i]-1 has not been seen
            element_of_seq = array[i] 
            length = 0
            while element_of_seq in s: # while the next element is in the set, increase the length by one 
                element_of_seq +=1
                length += 1
                if length > max_length:
                    max_length = length
            
    return max_length
    
print(longest_cons_subs(test_array))

4
4


In [10]:
# Find if an array is a subset of another array:

# Naive Implimentation with O(nlogn) complexity:
def check_if_arr2_is_subset_of_arr1(arr1, arr2): # assuming arr2 is a subset of arr1 and is smaller
    m = len(arr1)
    n = len(arr2)
    i = 0
    j = 0
    
    arr1.sort() 
    arr2.sort() 
  
    while i < n and j < m: 
        if arr1[j] < arr2[i]: 
            j += 1
        elif arr1[j] == arr2[i]: 
            j += 1
            i += 1
        elif arr1[j] > arr2[i]: # since both the arrays are sorted, there can't be an element in the long array bigger
            return False
        if j == m and i < n: # if there are still elements in arr2 that were not seen while arr1 is seen, return False
            return False
        if i == n: # if all the items are seen already, return True
            return True
        
    return True
  

test_arr1 = [11, 1, 13, 21, 3, 7] 
test_arr2 = [11, 3, 7, 1] 
  

print(check_if_arr2_is_subset_of_arr1(test_arr1, test_arr2))


# Hashing implimentation with O(n) complexity where n is the larger array
def find_if_a_is_a_subset_of_b(array_a, array_b): # array b is the larger array
   
    hash_set = set()
    for i in array_b:
        hash_set.add(i)
    
    # check if all the items of the smaller array are in the hash
    for i in range(len(array_a)):
        if array_a[i] not in hash_set:
            return False
    return True
        
print(find_if_a_is_a_subset_of_b(test_arr2, test_arr1))



True
True


In [11]:
# Print all pairs with given sum
# Ex: arr[] = {2, 5, 17, -1}, sum = 7, Output :  (2, 5)

def find_pairs_with_given_sum(array, k): 
    # put all items to a hash table
    hash_table = {}
    for i in range(len(array)):
        if array[i] not in hash_table.keys():
            hash_table[array[i]] = 'seen'
    pairs_list = []
    # check if hash table has items k-item for each item in the array
    for i in range(len(array)):
        pairing_item = k - array[i] 
        if pairing_item in hash_table.keys():
            pairs_list.append([pairing_item, array[i]])
    return pairs_list

test_array = [2,3,1,6,7,4,0]
k = 9
find_pairs_with_given_sum(test_array, k)

[[7, 2], [6, 3], [3, 6], [2, 7]]

In [12]:
# Find first repeated character

test_text = 'ajdfhajfh' # the answer should be 'a' as first repeated character
a_dict = {}
for i in test_text:
    if i not in a_dict.keys():
        a_dict[i] = 'seen once'
    else:
        print(i)
        break

a


In [13]:
# Find all zero sum subarrays in an array of numbers

test_array = [-6,5,1,6,1,6,-7,-2,-7,8,1,9] # output [-6,5,1], [1,6,-7] , [-2,-7,8,1]

def zero_sum_subarrays(array):
    # make the sum array
    sum_array = []
    total = 0
    for i in array:
        total += i
        sum_array.append(total)
    
    # loop over the sum array and if the item in the sum array is seen twice, find where it has seen earlier,
    # mark where it has been seen again, save the items at start+1 to end+1 indices 
    # if there is any item shows 0 in the sub array, mark the index save all the items before including the marked index
    results = []
    hash_items = {}
    for i in range(len(sum_array)):
        if sum_array[i] == 0: results.append(array[:i+1])
        if sum_array[i] in hash_items.keys():
            hash_items[sum_array[i]].append(i)
        else:
            hash_items[sum_array[i]] = [i]
        
    for k,v in hash_items.items():
        if len(v) > 1:
            for i in range(1,len(v)):
                results.append(array[v[i-1]+1 : v[i]+1])
                
        
    print(sum_array, hash_items) # to view
    return results
        
zero_sum_subarrays(test_array)
    
    
    

[-6, -1, 0, 6, 7, 13, 6, 4, -3, 5, 6, 15] {-6: [0], -1: [1], 0: [2], 6: [3, 6, 10], 7: [4], 13: [5], 4: [7], -3: [8], 5: [9], 15: [11]}


[[-6, 5, 1], [1, 6, -7], [-2, -7, 8, 1]]

In [14]:
# Check if two arrays are equal or not

test_array1 = [5,1,6,1,6,-2]
test_array2 = [1,6,6,1,-2,5]

def check_if_same(arr1,arr2):
    if len(arr1) != len(arr2): return False
    
    hash_table = {}
    for i in range(len(test_array1)):
        if test_array1[i] in hash_table.keys():
            hash_table[test_array1[i]] += 1
        else:
            hash_table[test_array1[i]] = 1
    
    hash_table2 = {}
    for i in range(len(test_array2)):
        if test_array2[i] in hash_table2.keys():
            hash_table2[test_array2[i]] += 1
        else:
            hash_table2[test_array2[i]] = 1
            
    for k, v in hash_table.items():
        v = hash_table[k]
        if k not in hash_table2.keys():
            return False
        if v != hash_table2[k]:
            return False
    return True
        
check_if_same(test_array1, test_array2)     
        
       

True

In [15]:
# Return the length and the list of items of the shortest supersequence of X and Y strings

# Dynamic Programming Approach:
import numpy as np

def shortest_supersequence(X, Y): 
    m = len(X)
    n = len(Y)
    memo_list = np.zeros([m+1, n+1], dtype = int)

    for i in range(1, m + 1): 
        for j in range(1, n+1): 
            memo_list[0][j] = j # if there is no item in the X string, the result is length of Y
            memo_list[i][0] = i # if there is no item in the Y string, the result is length of X
              
            if (X[i - 1] == Y[j - 1]):  
                memo_list[i][j] = 1 + memo_list[i - 1][j - 1] 
                   
            else: 
                memo_list[i][j] = 1 + min(memo_list[i - 1][j], memo_list[i][j - 1]) 
    
    print(memo_list) # to view
    print(memo_list[m][n]) # answer to the length of the supersequence
  
    i = m 
    j = n 
    result = []
    while i > 0 and j > 0: 
        if X[i - 1] == Y[j - 1]: 
            result.insert(0, X[i-1]) 
            i -= 1
            j -= 1

        elif memo_list[i - 1][j] > memo_list[i][j - 1]: 
            result.insert(0, Y[j-1]) 
            j -= 1

        else: 
            result.insert(0, X[i-1]) 
            i -= 1

    # if j == 0
    while i > 0: 
        result.insert(0, X[i-1])  
        i -= 1

    
    #if i == 0
    while j > 0: 
        result.insert(0, Y[j-1]) 
        j -= 1

  
    return result
    
test_x = "VKLAB"
test_y = "ZKADB"
shortest_supersequence(test_x, test_y)

[[0 1 2 3 4 5]
 [1 2 3 4 5 6]
 [2 3 3 4 5 6]
 [3 4 4 5 6 7]
 [4 5 5 5 6 7]
 [5 6 6 6 7 7]]
7


['Z', 'V', 'K', 'L', 'A', 'D', 'B']

In [16]:
# Find the smallest window that contains all characters of a given string   

import numpy as np
def find_sub_string(string):  
    ctr, start_pos, start_pos_index, min_len = 0, 0, -1, np.inf
    curr_count = {}
    for i in range(len(string)): 
        if string[i] in curr_count.keys():
            curr_count[string[i]] += 1
        else:
            curr_count[string[i]] = 1
            ctr += 1 # the number of characters seen only once

        if ctr == len(set(string)): # starting from index 0 to the index i, all items are already seen once 
            while curr_count[string[start_pos]] > 1: 
                curr_count[string[start_pos]] -= 1
                start_pos += 1
            len_window = i+1 - start_pos 
            if min_len > len_window: 
                min_len = len_window 
                start_pos_index = start_pos 
            return string[start_pos_index: start_pos_index + min_len] 

test_string = "asdaewsqtwwmsa"
print(find_sub_string(test_string))


# Easier way of finding the smallest window that contains all characters of a given string:
# Discard all items that are seen more than once from both ends and then output the middle part of the string

def find_sub_string(string):  
    
    curr_count = {}
    for i in range(len(string)): 
        if string[i] in curr_count.keys():
            curr_count[string[i]] += 1
        else:
            curr_count[string[i]] = 1
            
    start = 0
    end = len(string)-1
    while curr_count[string[start]] > 1:
        start += 1
        
    while curr_count[string[end]] > 1:
        end -= 1
        
    return test_string[start:end+1]
    
test_string = "asdaewsqtwwmsa"
print(find_sub_string(test_string))

daewsqtwwm
daewsqtwwm


In [17]:
# Function to find smallest window containing all characters of 'str2' in 'str1' 
import numpy as np

def smallest_window_in_str1_having_str2(str1, str2):  
    
    assert(len(str1) > len(str2))
    hash_str2 = {}
    for i in range(len(str2)):
        if str2[i] in hash_str2.keys():
            hash_str2[str2[i]] += 1
        else:
            hash_str2[str2[i]] = 1
    
    hash_str1 = {}
    for i in range(len(str1)):
        if str1[i] in hash_str1.keys():
            hash_str1[str1[i]] += 1
        else:
            hash_str1[str1[i]] = 1

    start = 0
    min_len = 0
    for j in range(len(str1)): 
        if str1[j] == ' ': # this is important to skip since key == ' ' returns None
            continue
        exist = hash_str2.get(str1[j]) # check if it exists and if there are other letters to be seen later
        if exist == None or hash_str1[str1[j]] > hash_str2[str1[j]]: 
            hash_str1[str1[j]] -= 1
            start += 1
            len_window = j - start 
            if len_window > min_len:  
                min_len = len_window  
                start_index = start  

    return string[start_index + 1 : start_index + min_len]  

string = "this is a test string"
pat = "tist"
print(smallest_window_in_str1_having_str2(string, pat))

t stri


In [18]:
# Find first element to occur k times in a string

test_string = 'askdafkjaiek' 
k = 3
# answer is 'a'
hash_string = {}
for i in range(len(test_string)):
    if test_string[i] in hash_string.keys():
        hash_string[test_string[i]] += 1
        if hash_string[test_string[i]] == k:
            print(test_string[i])
            break
    else:
        hash_string[test_string[i]] = 1

a
