In [1]:
# Reverse the words in a string. Ex: Input = “volkan loves ice cream”  , Output = “cream ice loves volkan"

def reverse_words(a_string):
    words = a_string.split(" ") # makes a list
    reversed_words = []
    for i in range(len(words)):
        reversed_words.insert(0, words[i])
    return " ".join(reversed_words)

test_text = "volkan loves ice cream"
reverse_words(test_text)


'cream ice loves volkan'

In [2]:
# Reverse the words in a string in coding interview style without using the split and join functions

def rev_words(string):
    if " " not in string: return [string] # if the string has one word only, return the word
    result_list = []
    start = 0
    string = string + " " # put an empty string after each word so that the words can be split until the last one
    for i, ch in enumerate(string):
        if ch == " ":
            result_list.insert(0, string[start:i])
            start = i + 1
    # the result list is a list of words of the original string in reversed order
    # combine each word 
    joined_str = ""
    for i in result_list:
        joined_str += i + " "
    return joined_str[:-1] # since the last word gets an " " as well, remove it before returning the joined_str

rev_words("volkan loves ice cream")


'cream ice loves volkan'

In [3]:
# Permutations of a string

def permutations_of_a_string(string, all_perm = None, perm_item = None):
    if all_perm == None: all_perm = []
    if perm_item == None: perm_item = []
    # base case
    if len(string) == 0: 
        all_perm.append(perm_item)
        return
    for i in range(len(string)): # for all items in the string
        remaining = string[:i] + string[i+1:]
        if remaining != None:
            permutations_of_a_string(remaining, all_perm, perm_item + [string[i]])
    
    return ["".join(items) for items in all_perm]

permutations_of_a_string("but")

['but', 'btu', 'ubt', 'utb', 'tbu', 'tub']

In [4]:
# Finding the longest palindromic sub-string in O(n^2) time and O(1) space complexity

string = "vlkasjsakwe"

# create a function that takes a string and outputs the lpss
def lps(string):
    if len(string) <= 1: return string
    longest = 0
    for i in range(1, len(string)):
        if len(string) % 2 == 1: # if the length is odd
            low = i-1
            high = i + 1
            while low > 0 and high < len(string)-1:
                if string[low] == string[high]:
                    length = high - low + 1
                    if length > longest:
                        longest = length
                        start = low
                low -= 1
                high += 1
            
        else: # if the length is even
            low = i
            hight = i + 1 
            while low > 0 and high < len(string)-1:
                if string[low] == string[high]:
                    length = high - low + 1
                    if length > longest:
                        longest = length
                        start = low
                low -= 1
                high += 1
  
    return string[start : start + longest]

lps(string)


'kasjsak'

In [5]:
# Recursively remove adjacent duplicates from a string keeping the first of the duplicates in place

string = "vlkkasjjsake"

def remove_adj_duplicates(string):
    if len(string) == 1: return string
    if string[0] == string[1]:
        return remove_adj_duplicates(string[1:])
    else:
        clean_text = string[0] + remove_adj_duplicates(string[1:])
        return clean_text
    
remove_adj_duplicates(string) 


'vlkasjsake'

In [6]:
# Recursively remove duplicates from a string erasing both duplicates after each time the function is called
# Ex: test_string = "azxxzyb", result : ayb

def rmv_adj_duplicates(string, i):
    if not string: return ""
    if i == len(string) - 1: return string
    if len(string) == 1: return string
    if string[i] == string[i+1]:
        return rmv_adj_duplicates(string[:i] + string[i+2:], i-1)
    else:
        return rmv_adj_duplicates(string, i+1)

    
test_string = "azxxzyb"
rmv_adj_duplicates(test_string, 0)


'ayb'

In [7]:
# Reverse a string

def reverse_string(string):
    rotated = ""
    if len(string) <= 1: return string
    for i in reversed(range(len(string))):
        rotated += string[i]
    return rotated
    
print(reverse_string('Heelo'))   


oleeH


In [8]:
# Check if a string can be obtained by rotating (shifting) another string with 2 places
# Ex: str1 = "volkan" can be shifted to the left as: "anvolk" or to the right as: "lkanvo"

def rotate_string_with_2_char(str1, str2):
    left_shift = str1[2:] + str1[:2]
    right_shift = str1[-2:] + str1[:-2]
    if left_shift == str2 or right_shift == str2:
        return True
    else:
        return False

str1 = "volkan"
str2 = "anvolk"
rotate_string_with_2_char(str1, str2)


True

In [9]:
# Create an array with T and F values to show whether the tendency of the numbers in array are going up or not 
# mark T for increasing and F for decreasing in REVERSE order. If the values are the same, keep the previous tendency
# ex: [1000, 100, 500, 50, 1, 1, 5] output [T, F, T, F, F, F, T]. Start from the last index which is assigned True. 

import numpy as np
def tendency(array):
    tendency_array = np.zeros(len(array))
    last_item = len(array) - 1
    tendency_array[last_item] = True
    if len(array) == 1: return total
    for i in reversed(range(len(array)-1)):
        if i >= 1:
            if array[i-1] > array[i]:
                tendency_array[i-1] = True
            elif array[i-1] < array[i]:
                tendency_array[i-1] = False
            elif array[i-1] == array[i]:
                tendency_array[i-1] = tendency_array[i]
        if i == 0:
            tendency_array[0] = True
    return tendency_array

test_array = [1000, 100, 500, 50, 1, 1, 5]  # up down up down down down up
tendency(test_array)



array([1., 0., 1., 1., 0., 0., 1.])

In [10]:
# Output roman numbers to decimals 
# Strategy: Check the last letter of the roman string and add it as total value of the string. Keep moving 
# towards the beginning of the string. Keep a flag to show whether the value should be decreased or increased if 
# the same letter is seen again. If the next letter is lower, mark the flag to "decrease" and substract it from the 
# total but if the value is bigger than the previous one, add the value to the total, and mark the flag to "increase" 

a_dict = {'I': 1, 'V': 5, 'X' : 10, 'L': 50, 'C': 100, 'D': 500, 'M':1000}
test_string = 'MCCMXIIV'


import numpy as np
def tendency(string, a_dict):
    tendency_array = np.zeros(len(string))
    last_item = len(string) - 1
    tendency_array[last_item] = True
    for i in reversed(range(len(string))):
        if i >= 1:
            if a_dict[string[i-1]] > a_dict[string[i]]:
                tendency_array[i-1] = True
            elif a_dict[string[i-1]] < a_dict[string[i]]:
                tendency_array[i-1] = False
            elif a_dict[string[i-1]] == a_dict[string[i]]:
                tendency_array[i-1] = tendency_array[i]
        if i == 0:
            tendency_array[0] = True
    print(tendency_array) # to view
    return tendency_array


def convert_roman_into_decimal(string, a_dict): # input is string for roman letters and output is the decimal number
    tendency_array = tendency(string, a_dict)
    total = 0
    for i in range(len(string)):
        item_val = a_dict[string[i]]
        if tendency_array[i] == True:
            total += item_val
        else:
            total -= item_val

    return total


convert_roman_into_decimal(test_string, a_dict)




[1. 0. 0. 1. 1. 0. 0. 1.]


1813

In [11]:
# Alternative solution to the problem above

def roman_to_decimal(string):
    if len(string) == 0: return None
    last_letter = string[-1]
    value_of_the_last_letter = a_dict[last_letter]
    total = value_of_the_last_letter
    memory = np.zeros(len(string))
    memory[-1] = True
    for i in reversed(range(1, len(string))):
        curr_index = i
        curr_roman_text = string[curr_index]
        value_curr_roman_text = a_dict[curr_roman_text]
        next_index = i-1
        next_roman_text = string[next_index]
        value_of_next_roman_text = a_dict[next_roman_text]
        if value_of_next_roman_text > value_curr_roman_text:
            total += value_of_next_roman_text
            memory[next_index] = True
        elif value_of_next_roman_text < value_curr_roman_text:
            total -= value_of_next_roman_text
            memory[next_index] = False
        else:
            memory[next_index] = memory[curr_index]
            if memory[next_index] == True:
                total += value_of_next_roman_text
            else:
                total -= value_of_next_roman_text
    print(memory)            
    return total

test_string = 'MCCMXIIV' #:1813
roman_to_decimal(test_string)

[1. 0. 0. 1. 1. 0. 0. 1.]


1813

In [12]:
# Write a function that outputs the anagram of a text

def anagram(text, results = None, solutions = None): 
    if results == None: results = []
    if solutions == None: solutions = []
    if len(text) == 0: 
        results.append(solutions)
        return
    for i, n in enumerate(text):
        remaining = text[:i] + text[i+1:]
        if remaining != None:
            anagram(remaining, results, solutions + [n])
    return [''.join(i) for i in results]

test_text = 'abc'
test_set = list(test_text)
anagram(test_set)



['abc', 'acb', 'bac', 'bca', 'cab', 'cba']

In [13]:
# Remove duplicates in an array or string in 3 different ways, using list comprehension, set, and dictionary.

# OPTION !:
messy_array = [2,3,5,26,243,545,234,2,4,25,4,6,6,5]
remove_duplicates_of_array = [n for i,n in enumerate(messy_array) if n not in messy_array[:i]]
print(remove_duplicates_of_array)

messy_text = 'akdfjaklfakfkasfjkalsjflasjdf'
messy_text = list(messy_text)
remove_duplicates_of_string = [n for i,n in enumerate(messy_text) if n not in messy_text[:i]]
print(remove_duplicates_of_string)

# OPTION 2:
set_of_text = set(messy_text)
print(set_of_text)


# OPTION 3:
a_dict = {}
for i in range(len(messy_text)):
    if messy_text[i] in a_dict:
        continue
    else:
        a_dict[messy_text[i]] = 'True'    
print(a_dict.keys())
        


[2, 3, 5, 26, 243, 545, 234, 4, 25, 6]
['a', 'k', 'd', 'f', 'j', 'l', 's']
{'j', 'l', 'd', 'f', 'k', 'a', 's'}
dict_keys(['a', 'k', 'd', 'f', 'j', 'l', 's'])


In [14]:
# Write a dynamic programming based program to find minimum number insertions (addition) needed to make a palindrome 

# Examples:
# ab: Number of insertions required is 1 i.e. bab    aa: Number of insertions required is 0 i.e. aa
# abcd: Number of insertions required is 3 i.e. dcb + abcd

# Algorithm:
# The table should be filled in diagonal fashion. For the string abcde, 0….4, 
# the following should be order in which the table is filled:

# Gap = 1: (0, 1) (1, 2) (2, 3) (3, 4)  --> l, h values
# Gap = 2: (0, 2) (1, 3) (2, 4)
# Gap = 3: (0, 3) (1, 4)
# Gap = 4: (0, 4)

import numpy as np

def min_insertions_for_palindrome(str1): # look for similar letters at the edges and calculate the steps needed to make it similar
    n = len(str1)
    # Create a table of size n*n to store minimum number of insertions  
    # needed to convert str1[l..h] to a palindrome. Fill the table diagonally
    table = np.zeros([n,n], dtype = int)
    for gap in range(1, n): 
        l = 0
        for h in range(gap, n): 
            # if the beginning and ending letters are the same, move one index towards inner part of the string
            # Ex iovoi then the next step is to check ovo
            if str1[l] == str1[h]: 
                table[l][h] = table[l + 1][h - 1] 
            # if the letters at both edges are not the same, look for either moving from one side or the other
            # find the minimum and add one more step
            else: 
                table[l][h] = (min(table[l][h - 1], table[l + 1][h]) + 1) 
            l += 1
    
    print(table)
    # Return minimum number of insertions for str1[0..n-1] 
    return table[0][n - 1]; 
  
# Driver Code 
test_str = "voii"
print(min_insertions_for_palindrome(test_str)) 
  


[[0 1 2 2]
 [0 0 1 1]
 [0 0 0 0]
 [0 0 0 0]]
2


In [15]:
# Reminder for diagonal insertion order to a table

n = 4
table = np.zeros([n,n], dtype = int)
for gap in range(1, n):
    i = 0
    for j in range(gap, n):
        table[i,j] = j + gap - 1 
        i += 1
        
print(table)     

[[0 1 3 5]
 [0 0 2 4]
 [0 0 0 3]
 [0 0 0 0]]


In [16]:
# Find the length of the longest substring without repeating characters by using a sliding window method

def longest_substr_with_dist_chars(s):
    window = set()
    left = 0 
    max_length = 0
    for right in range(len(s)):
        while s[right] in window:# if the new element on the right is already in the window, 
            # take off all the previous elements until there is no common element left: Ex: remove: abc from abcdefgc
            window.remove(s[left])
            left += 1
        window.add(s[right])
        if len(window) > max_length:
            max_length = len(window)
            start_index = left
    lcs_with_dist = s[start_index : start_index + max_length]
    return lcs_with_dist
    
string = "kakoernejf"
longest_substr_with_dist_chars(string)

'akoern'

In [17]:
# An alternative approach to find the length of the longest substring without repeating characters 

import numpy as np
def longest_substring_with_dist_chars(string):
    n = len(string)
    max_length = 0
    for i in range(0, n):
        for j in range(i, n):
            seen_letters = string[i:j+1]
            if len(string[i:j+1]) == len(set(string[i:j+1])):
                length = j-i
                if length > max_length:
                    max_length = length
                    mark_start_ind = i
                    mark_end_ind = j
                    
    lcs = string[mark_start_ind : mark_end_ind + 1]          
    return lcs

string = "kakoernejf"
longest_substring_with_dist_chars(string)
            

'akoern'

In [18]:
# Dynamic Programming Solution to longest common substring of two strings problem

import numpy as np
X = 'qalkfaoik'
Y = 'qfaoianok'

def LCsubstring(x, y):
    n = len(x)
    m = len(y)
    # create a 2D known list to store the sub-solutions
    known_list = np.zeros([n+1, m+1], dtype = int)
    # create a list to return the solution
    lcs = []
    # set a variable to find the maximum length
    longest = 0
    # loop over the rows 
    for i in range(1, n+1):
        # loop over the columns
        for j in range(1, m+1):
            # if there is a match, move down one step diagonally on the matrix and increase the value by one
            if x[i-1] == y[j-1]:
                known_list[i][j] = known_list[i-1][j-1] + 1
                c = known_list[i][j]
                if c > longest: # if it is the longest substring
                    longest = c
                    lcs = []
                    lcs.append(x[i-longest: i])

    print(known_list)
    return lcs            
            
LCsubstring(X,Y)          

[[0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1]
 [0 0 1 0 0 0 0 0 0 0]
 [0 0 0 2 0 0 1 0 0 0]
 [0 0 0 0 3 0 0 0 1 0]
 [0 0 0 0 0 4 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1]]


['faoi']

In [19]:
# Make an atoi() function with python 
# atoi in C language takes a string (which represents an integer) as an argument and returns its value of type int.

def atoi(string): 
    total = 0
    for i in range(0, len(string)): 
        number = (ord(string[i]) - ord('0')) # simply the string is changed to integer
        # position of the number in decimal system
        pos = 10**(len(string)-i-1) 
        # position * number is its current value in decimal system
        total += number * pos
    return total
atoi('291')
  
# atoi in python is simply: int(string)

291

In [20]:
# Implement strstr function. Find the starting index of substring within a string (or its first occurence)
# if substring is not found return -1

def strstr(string, substr):
    if len(substr) > len(string) : return
    n = len(substr)
    for i in range(len(string)-n):
        if string[i:i+n] == substr:
            print(string[i:i+n])
            return i
    return -1

strstr('ayfjasf', 'fja')



fja


2

In [21]:
# Write a function that outputs the Longest Common Prefix of multiple strings
# Example:  if input: 'flower', 'flow', 'floight' the output is: "flo"
    
def longest_common_prefix(*args):
    # loop over the elements of the first word
    for i in range(len(args[0])):
        # loop over all the elements in args
        for j in range(1, len(args)):
            # if the index at the first word is not seen in other words in the same place, 
            # return the previous elements
            # if the length of any word is equal to the first word, return the previous elements as well.
            if args[0][i] != args[j][i] or len(args[j]) == i:
                return args[0][:i]
longest_common_prefix('hela', 'hello', 'helicopter')    
 

'hel'